### ISSUE TITLE
Can I make Asynchronous Tasks ?

### ISSUE THREAD

**Issue by ufo911** [viniciuschiele/flask-apscheduler#100]
Like Celery Can I make such tasks?

**Comment by viniciuschiele** [comment]
Hi,

All tasks are executed in the background on its own thread.

**Comment by ufo911** [comment]
@viniciuschiele So I can use this scheduler instead of celery ? In addition how can I manage the results from tasks ?

**Comment by viniciuschiele** [comment]
Hi,

No, you can't get the result from a task like in Celery.

APScheduler is only meant to run Python functions in background based on a range interval, if you need anything else Celery looks a better option.
