### ISSUE TITLE
How to bind mysql and flask_apscheduler

### ISSUE THREAD

**Issue by alrne** [viniciuschiele/flask-apscheduler#104]
My configuration information in the mysql database, you need to implement cron according to the information in mysql, how to achieve。

this my solution:

while True:
    scheduler_service = SchedulerService()
    job_list = scheduler_service.get_new_job()
    modify_job = scheduler_service.get_alter_job()
    remove_job = scheduler_service.get_need_remove_job()
    if job_list:
        for job in job_list:
            scheduler.add_job(job['data'], trigger="corn",
                              minute=job['minute'],
                              hour=job['hour'],
                              week=job['week'],
                              month=job['month'])
    elif modify_job:
        pass
    elif remove_job:
        pass

**Comment by viniciuschiele** [comment]
Hi,

Not sure if I understood your question but you can add a cron job manually:
```python
scheduler.add_job("job_id", job_func, trigger="cron", hour=job['hour'], minute=job['minute'])
```
For more details check this out: https://apscheduler.readthedocs.io/en/latest/modules/triggers/cron.html

**Comment by alrne** [comment]
thank you，  I have solved my problem.I have some tasks that are stored in the db ,and some are fixed in th e system. I found a solution under /flask-apscheduler/edit/master/COMMON-ISSUES.md , whatever ,thank for you answer my question.
