### ISSUE TITLE
scheduler with UWSGI cause "is taking too much time to die...NO MERCY !!!"

### ISSUE THREAD

**Issue by johaven** [viniciuschiele/flask-apscheduler#106]
**Versions**
Flask-APScheduler  1.8.0
uwsgi-2.0.17.1

**UWSGI conf**
```ini
...
master = true
enable-threads = true
thunder-lock = true
processes = 4
threads = 4
offload-threads = 4
max-requests = 1000
module = webapp
callable = app
vacuum = true
...
```
**Problem**
All my tasks are ok (executed, done without errors).
Since i use this lib on my flask app, when i reload gracefully UWSGI, i get a long timeout (30s to 60s) and this message:

```
worker 1 (pid: 9114) is taking too much time to die...NO MERCY !!!
worker 2 (pid: 9119) is taking too much time to die...NO MERCY !!!
worker 3 (pid: 9127) is taking too much time to die...NO MERCY !!!
worker 4 (pid: 9135) is taking too much time to die...NO MERCY !!!
```
If i remove scheduler init from my app, i have no problem, the reload take 3s

**Flask init**
```python
scheduler = APScheduler()
scheduler.init_app(app)
scheduler.start()
atexit.register(lambda: scheduler.shutdown()) # i tried this but same problem
```

**Comment by viniciuschiele** [comment]
Hi,

I've tried your uwsgi config and it works well with my own tasks.

It must be something your task is using that causes it to hang.

Would you be able to provide an example that replicates the problem?

**Comment by johaven** [comment]
I solved my problem using the uwsgi mule solution.

My tasks use redis and mysql and the mix of threads and pools in addition to flask contexts was too complicated to debug.
