### ISSUE TITLE
ValueError: Unable to determine the name of the local timezone 

### ISSUE THREAD

**Issue by asubramani82** [viniciuschiele/flask-apscheduler#109]
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki).

looks like there is fix in apscheduler version 3.6.0

**Comment by asubramani82** [comment]
working locally in mac , but does not work in  docker in kubernetes .

**Comment by arrancorbett** [comment]
I've also just come across this issue.

**Comment by chinared-hub** [comment]
How to solve this problem, afflictive

**Comment by chinared-hub** [comment]
ok，i know how to fix it......

**Comment by chinared-hub** [comment]
> 
> 
> working locally in mac , but does not work in docker in kubernetes .

`docker run --name  mydocker -p 5000:5000 -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro`

start the docker and added `-v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro` 

I don't know if that would satisfy your situation

**Comment by ndragon798** [comment]
You can add these to the file and it will allow you to set your time zone
```
import os

os.environ['TZ']= 'America/New_York'
```

**Comment by ak82091157** [comment]
You can add a timezone file to the /etc directory.
![image](https://user-images.githubusercontent.com/9837528/68573357-87eeab00-04a2-11ea-97d7-69c3ec1cc9a7.png)

**Comment by Syed-Waleed-Shah** [comment]
> You can add these to the file and it will allow you to set your time zone
> 
> ```
> import os
> 
> os.environ['TZ']= 'America/New_York'
> ```

this worked thanks

**Comment by zn845639326** [comment]
I also faced this problem.
The sulotion is that I add this code `RUN rm /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime` in my Dockerfile.

The whole story:
Before solved, tzlocal return `local`, 
```
>>> import tzlocal
>>> tzlocal.get_localzone()
<DstTzInfo 'local' CST+8:00:00 STD>
>>> print(tzlocal.get_localzone())
local
```
See the site https://pypi.org/project/tzlocal/
> Please note that if you getting a time zone called local, this is not a bug, it’s actually the main feature of tzlocal, that even if your system does NOT have a configuration file with the zoneinfo name of your time zone, it will still work.

But in my docker, apscheduler would be failed work with timezone `local`. So I add this `RUN rm /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime` in my Dockerfile. You can replace `Asia/Shanghai` with what you need.

Then the problem was solved:

```
>>> import tzlocal
>>> tzlocal.get_localzone()
<DstTzInfo 'Asia/Shanghai' LMT+8:06:00 STD>
>>> print(tzlocal.get_localzone())
Asia/Shanghai
```
