### ISSUE TITLE
what the python version does the package support???

### ISSUE THREAD

**Issue by LabroShine** [viniciuschiele/flask-apscheduler#110]
when i try the example code of,
from flask import Flask
from flask_apscheduler import APScheduler

class Config(object):
    JOBS = [
        {
            'id': 'job1',
            'func': 'job1',
            'args': (1, 2),
            'trigger': 'interval',
            'seconds': 10
        }
    ]

    SCHEDULER_API_ENABLED = True

def job1(a, b):
    print(str(a) + ' ' + str(b))

if __name__ == '__main__':
    app = Flask(__name__)
    app.config.from_object(Config())

    scheduler = APScheduler()
    scheduler.init_app(app)
    scheduler.start()

    app.run()
it doesn't work.

**Comment by viniciuschiele** [comment]
It works fine in Python >= 2.7 or Python >= 3.4.

What is the error you get?

**Comment by LabroShine** [comment]
> It works fine in Python >= 2.7 or Python >= 3.4.
> 
> What is the error you get?
Sorry, more clearly, i am using python 3.6.8  and the flask is 1.0.2。I try to follow your example code, to write my own code, so i ran the code above. i can not see anything, although the code is running...

**Comment by LabroShine** [comment]
May be the image can give you some useful informations.
Sorry, I have trouble in uploading the image...

**Comment by LabroShine** [comment]
![Uploading image.png…]()

**Comment by LabroShine** [comment]
May be the image can give you some useful informations.
Sorry, I have trouble in uploading the image...

**Comment by LabroShine** [comment]
![Uploading image.png…]()

**Comment by viniciuschiele** [comment]
I can't see any issue, I've just run it with ```python jobs.py```, and every 10 secs I see the message being printed on the console

**Comment by LabroShine** [comment]
Can you show me your file structure?

**Comment by viniciuschiele** [comment]
I'm using this file: https://github.com/viniciuschiele/flask-apscheduler/blob/master/examples/jobs.py

**Comment by LabroShine** [comment]
I copy the code file to a new file, and try to run it.Firstly, if i put the `app = Flask(__name__)` just as before, it will be throw an error, with message "Error: Failed to find Flask application or factory in module "app". Use "FLASK_APP=app:name to specify one.", so to solve the problem, i put the sentence ahead of `if __name__ == '__main__':`， this modification can make the code run, but 10 secs later, no message printed con the console.

**Comment by viniciuschiele** [comment]
it looks like you are using Flask CLI to run the app, I renamed the file jobs.py to app.py and removed the line `__name__ ==  '__main__'` and it worked for me.

that is the code that I ran before using `flask run`

```python
from flask import Flask
from flask_apscheduler import APScheduler


class Config(object):
    JOBS = [
        {
            'id': 'job1',
            'func': 'app:job1',
            'args': (1, 2),
            'trigger': 'interval',
            'seconds': 10
        }
    ]

    SCHEDULER_API_ENABLED = True


def job1(a, b):
    print(str(a) + ' ' + str(b))


app = Flask(__name__)
app.config.from_object(Config())

scheduler = APScheduler()
scheduler.init_app(app)
scheduler.start()

app.run()
```

**Comment by LabroShine** [comment]
I just try the code you post, it works..., thank you

**Comment by LabroShine** [comment]
One more question. If i want to keep the line __name__ == '__main__',  how can i do to make the code works???

**Comment by LabroShine** [comment]
you said i ran the code using flask CLI, it's true, but what the difference between flask CLI and CMD "python app.py"?
And the format of `'func': 'app:job1',` can i just use job1 instead of 'app:job1'?

**Comment by viniciuschiele** [comment]
Not really sure what are the differences but I looks like Flask CLI doesn't set the variable ```__name__ = '__main__'```

The ```func``` attribute has to be the full path of the function, in this case ```app``` is the module name (app.py) where the function is located.
