### ISSUE TITLE
Cannot start() after shutdown()

### ISSUE THREAD

**Issue by hcaihao** [viniciuschiele/flask-apscheduler#112]
How to restart after shutdown? Do I need re init or re add jobs?

**Comment by viniciuschiele** [comment]
If you are using the in-memory job store (default), all jobs are deleted when the scheduler is shutdown

**Comment by hcaihao** [comment]
I use Config to add jobs, why the job still runing after shutdown?

```
class Config(object):
    JOBS = [
        {
            'id': 'query_all_order',
            'func': interface.query_all_order,
            'args': (timedelta(minutes=20),),
            'trigger': 'cron',
            'hour': '0-4,6-23',
            'second': '*/10'
        }
    ]



    app.config.from_object(Config())
    scheduler.init_app(app)
    scheduler.api_enabled = True
    scheduler.start(paused=False)
```

**Comment by viniciuschiele** [comment]
What loads the jobs is the method **init_app**, you would need to call it every time you start the scheduler.

That happens because the in-memory job store loses all its jobs when the scheduler gets shutdown, so you need to re-load them to the job store

**Comment by hcaihao** [comment]
I see, tks.
