### ISSUE TITLE
job can't modify when use trigger class

### ISSUE THREAD

**Issue by vipwangtian** [viniciuschiele/flask-apscheduler#113]
I got an exeception when i modified a job with trigger class like this
`modify_job(job_id, trigger=CronTrigger.from_crontab(job_crontab))`
then i find below code in pop_trigger function, it seems that modify_job doesn't support trigger class
![image](https://user-images.githubusercontent.com/32926504/63315239-ffe28480-c33c-11e9-99f3-a66f9b158a60.png)

**Comment by viniciuschiele** [comment]
It doesn't, the trigger parameter is the trigger type name.

You can use it like that:

```python
modify_job(job_id, trigger='cron', year=2019, month=08, day=28, ...)
```
