### ISSUE TITLE
control apscheduler cross request

### ISSUE THREAD

**Issue by changyushun** [viniciuschiele/flask-apscheduler#114]
suppose I want let admin user to start apscheduler in admin page and let someone else to add or remove job in other page. apscheduler need save somewhere globally. I try save apscheduler in g but no working because it's only alive in a request. how to achieve this purpose ?

**Comment by viniciuschiele** [comment]
Hi,

You need to tell APScheduler to save the jobs in a database like SQLite, MySQL, ...

That is an example: https://github.com/viniciuschiele/flask-apscheduler/blob/master/examples/flask_context.py#L32

**Comment by changyushun** [comment]
thanks.
but my goal is try to add or modify job in another blueprint route function. all the example code implement apscheduler in one python file.

**Comment by viniciuschiele** [comment]
Sorry for the delay,

APScheduler doesn't live only in the request.

Would you mind sharing your code with blueprints? I can eventually add an example using blueprints.

**Comment by changyushun** [comment]
hello @viniciuschiele 
I found it's more complicated to save APScheduler in g and no working.
according flask document

> The g name stands for “global”, but that is referring to the data being global within a context. The data on g is lost after the context ends, and it is not an appropriate place to store data between requests. Use the session or a database to store data across requests. 

so I just treat APScheduler as another module in blueprint router, my sample below :

app.py (it's our app factory, we create flask and APScheduler)
```
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from flask import Flask
from flask_apscheduler import APScheduler
from mysql import client


scheduler = APScheduler()

app = Flask(__name__)

if __name__ == '__main__':
    
    client.init_db(app)
    scheduler.init_app(app)
    scheduler.start()
    from routes import worker
    app.register_blueprint(worker.app)
    app.run()
else:
    
    client.init_db(app)
    scheduler.init_app(app)
    scheduler.start()
    from routes import worker
    app.register_blueprint(worker.app)

```

worker.py (it's the blueprint router, we let user control job here)
```
from flask import Blueprint
from app import scheduler
from mysql.client import get_db
from app import app as flaskapp
import os

app = Blueprint("worker",__name__,url_prefix="/worker")

def write_log():
    print("write log fire")
    with flaskapp.app_context():
        db = get_db()
        cur = db.cursor()
        cur.execute("insert `log` (`text`) values (%s)","write log fire")
    
@app.before_request
def before():
    # check which process handler this request
    print("pid = {}".format(os.getpid()))


@app.route("/", methods=['GET'])
def index():
    return "state {}".format(scheduler.state)

@app.route("/resume")
def start():
    scheduler.resume()
    return "worker resume"

@app.route("/pause")
def stop():
    scheduler.pause()
    return "worker pause"

@app.route("/add")
def add_job():
    scheduler.add_job(
        id="write_log",
        func=write_log,
        trigger="interval",
        seconds=10,
    )
    return "add job done"

@app.route("/remove")
def remove():
    scheduler.remove_job("write_log")
    return "remove job done"


```

> BUT if you use gunicorn and set multiple worker. you will find each request add/remove job is bind to different worker process. that mean user will remove job in B worker process and B worker process does not have job added before. Exception fire.  my blue print before_request method show this problem. gunicorn --preload mode setting no help at all. maybe redis-queue will be another answer for multiple worker flask web app.

**Comment by viniciuschiele** [comment]
APScheduler doesn't work well with multiple gunicorn workers because it would run the same job multiple times (one in each worker). If you need to scale your app I would recommend you using Celery.
