### ISSUE TITLE
Unable to use oswalk from a job called by flask-apscheduler

### ISSUE THREAD

**Issue by igoham** [viniciuschiele/flask-apscheduler#116]
Hello,

Below is a small snippet.
I am funding once I call the initate_parsing function from the job configuration once i hit the for statement the code inside that statement doesn't execute. Has anyone run into this issues before?

Also path_to_xml_files is on d:\dev\xml on my dev system and /opt/parsing/xml on my prod system - not sure if its relevant but thought i should include.

`def initate_parsing(path_to_xml_files):
    for root, dirs, files in os.walk(path_to_xml_files, topdown=False):
        for name in files:
            temp_path_ = os.path.join(root,name)`

**Comment by viniciuschiele** [comment]
Hi,

I would need some sample code to figure out the problem.
