### ISSUE TITLE
Flask context with a background task

### ISSUE THREAD

**Issue by AlKult** [viniciuschiele/flask-apscheduler#117]
Hi,

I'm not sure if what I'm having here is a real issue or just me misunderstanding something, so at this time please treat it as a call for advice. :)

I'm trying to make Flask run a periodic background task without having to associate the task with a route and, more importantly, having to call the route in order to run the task.
The issue I'm having is that when used in a Flask application factory, Flask context isn't being passed to the function that I want periodically executed.

In order to demo the issue, I've created this simplistic app:
|-- flaskcontext
|   |-- __init__.py
|   |-- wsgi.py
|   |-- main
|   |   |-- routes.py
|   |   `-- utils.py
```
**wsgi.py**
from flaskcontext import create_app

app = create_app()

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True)
```
```
**__init__.py**
from flask import Flask
from flask_apscheduler import APScheduler

scheduler = APScheduler()

def create_app():
    app = Flask(__name__)

    with app.app_context():
        scheduler.init_app(app)

        from flaskcontext.main.routes import main
        app.register_blueprint(main)

        from flaskcontext.main.utils import test_context
        app.apscheduler.add_job(name='test_context', id=0, func=test_context, trigger="interval", seconds=5)
        scheduler.start()

        return app
```
```
**routes.py**
from flask import Blueprint
from flaskcontext.main.utils import test_context

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    utils_app_context = test_context()

    print('main.utils has_app_context', utils_app_context)

    return f'main.utils has_app_context {utils_app_context}'
```
```
**utils.py**
from flask import has_app_context

def test_context():
	print('main.utils has_app_context', has_app_context())
	
	return has_app_context()
```
I have utils.py alongside routes.py because in a prod factory, I'd have many helper functions which due to their volume I'd like to keep in a separate file (utils.py), whereas routes.py would contain only routes and imports so that routes.py would stay relatively clean and therefore easy to read.

After having started the app, if I go to the web page, it returns "main.utils has_app_context **True**" which indicates presence of Flask context in the test_context() function in the utils.py file at this time. However, in the console it prints "main.utils has_app_context **False**" every 5 seconds, which appears to be an indication that when the test_context() function is ran from the scheduler, no context is being passed to it.
Now as to why there _is_ context in the browser, I believe that is explained in the first paragraph of https://flask.palletsprojects.com/en/1.1.x/appcontext/
> The application context keeps track of the application-level data during **a request**, CLI command, or other activity. Rather than passing the application around to each function, the current_app and g proxies are accessed instead.

As for the context from the scheduler, the internet overwhelmingly seems to suggest using either `with app.app_context():` or `app.app_context().push()` as the panacea, but what I don't like about either is that in order to call them, I'd have to fork my application with either `app = create_app()` or `app = Flask(__name__)` which essentially would create another instance of my app whereas one instance of it is already running. Additionally, `app = Flask(__name__)` wouldn't account for anything I might have and most probably do have in my config.py unless I start redefining my config variables with `app.config.*` after the instantiation, and in case of creating the fork with `app = create_app()`, there's a danger or running into circular or recursive dependencies, plus it would start a whole bunch of other sub-apps which I don't need at this time.
Do you think these concerns are valid?
How would you implement what I'm after if that's possible at all?

Best regards,
Albert.

**Comment by viniciuschiele** [comment]
Hi,

Not sure if I understood your use case and why you think you would need to fork your app.

The Flask Context only exists within a Flask Request, when APScheduler runs a task, a Flask Request doesn't exist nor a Flask Context and APScheduler won't create one for you.

If you want to have access to the Flask Context within a task you can do that:

```python
def my_task():
    with scheduler.app.app_context():
        print(User.query.all())
```

I hope that helps.

**Comment by AlKult** [comment]
Hi Vinicius,

You understood correctly, and your answer does answer my question. I think I still don't fully understand Flask contexts as I didn't know there were other ways of accessing it, such as `scheduler.app.app_context()`. I was under impression there was only `app.app_context()` and that was it - but that one was loosing my context somewhere, and I couldn't understand why and where it was happening.
`with scheduler.app.app_context()` works like a charm for me.

Thank you!

Best regards,
Albert.
