### ISSUE TITLE
Having problems with job API, context issue?

### ISSUE THREAD

**Issue by hysoftwareeng** [viniciuschiele/flask-apscheduler#118]
I am having issues getting jobs and removing jobs in the scheduler. What I want to do is after running a scheduled job successfully, I want to remove it, but currently the job list is giving an empty list. Please see example below
```

from flask import Flask
from flask_apscheduler import APScheduler

scheduler = APScheduler()

class Config(object):
    JOBS = [
        {
            'id': 'job1',
            'func': 'advanced:job1',
            'args': (1, 2),
            'trigger': 'interval',
            'seconds': 10
        }
    ]

    SCHEDULER_API_ENABLED = True


def job1(a, b):
    print(str(a) + ' ' + str(b))
    print(scheduler.get_jobs()) # this is giving me an empty list. 
    scheduler.scheduler.remove_all_jobs() #not working

if __name__ == '__main__':
    app = Flask(__name__)
    app.config.from_object(Config())

    scheduler.init_app(app)
    scheduler.start()

    app.run()
```

**Comment by viniciuschiele** [comment]
That's likely happening because the task and the scheduler are in the same file, try adding a new file like tasks.py and move the job1 func into it.

**Comment by hysoftwareeng** [comment]
So that means I would need to pass the scheduler to the job function? Or can I just import it from the new file?

**Comment by viniciuschiele** [comment]
__init__.py
scheduler = APScheduler()

tasks.py
def job1(a, b):

main.py
app.run()

**Comment by hysoftwareeng** [comment]
Thanks, this has been fixed
