### ISSUE TITLE
render_template_string not working

### ISSUE THREAD

**Issue by mahavir155** [viniciuschiele/flask-apscheduler#123]
We have our own version of `APScheduler` which is as below since we wanted app context for every background job.

```
from flask_apscheduler import APScheduler as _BaseAPScheduler

class APScheduler(_BaseAPScheduler):
    def run_job(self, id, jobstore=None):
        with self.app.app_context():
            super().run_job(id=id, jobstore=jobstore)

```
`app.py` have the following:

```
scheduler = APScheduler()
scheduler.init_app(app)
scheduler.start()

kwargs = {"trigger": "cron", "minute": "*"}
scheduler.add_job('1job', create_checklist, **kwargs)

```
`create_checklist()` function looks like below

```
create_checklist():
     ..........some code.....
     ..........some code.....
     create_task()
     ..........some code.....
     ..........some code.....

create_task():
     ..........some code.....
     ..........some code.....
     **render_template_string()** => here it throws error since it cannot find app context
     ..........some code.....
     ..........some code.....

```

`render_template_string()` function try to access the context using `top()` function but it returns `NoneType`. We are also pushing the app_context().

Any help is appreciated if I am missing anything?

**Comment by viniciuschiele** [comment]
Hi,

The method `run_job` is only used to run the given job without scheduling it.

It looks like you want to create a Flask context for all jobs, I'm not 100% sure but I think you need to look into this class: https://apscheduler.readthedocs.io/en/latest/modules/executors/base.html

**Comment by viniciuschiele** [comment]
Let me know if you find a clean solution for that, I would like to include it in flask-apscheduler.
