### ISSUE TITLE
No trigger by the name "interval" was found

### ISSUE THREAD

**Issue by FLYYZJ** [viniciuschiele/flask-apscheduler#124]
Recently I want to use the  pyinstaller to package my flask app, which use the flask apscheduler to do some scheduler work. But I found although I can package my program successfully but when I start the exe, the error "No trigger by the name "interval" was found " occured. 
![image](https://user-images.githubusercontent.com/9419479/71221014-c418f500-2305-11ea-9eae-48f17bbe655f.png)
The original python code can be used. Part of my code that is used for add schedule is 
```python
scheduler = APScheduler()
def create_app():
    app = Flask(__name__)
    app.config.from_json(os.path.join(os.getcwd(), "config.json"))  
    register_blueprint(app)
    db.init_app(app)
    with app.app_context():
        db.create_all()
    scheduler.init_app(app)
    t1 = IntervalTrigger(seconds=3)
    scheduler.add_job("job_get_machine_status", get_machine_status, trigger=t1)
    t2 = IntervalTrigger(seconds=15)
    scheduler.add_job("job_get_sys_perso_module", get_sys_perso_module, trigger=t2)
    scheduler.start()
    return app
```
So I want to know whether I use the flask-scheduler in a wrong way or is there any other tricks I need to know to use pyinstaller to package the python program with flask-apscheduler?

**Comment by viniciuschiele** [comment]
Interesting issue, could you try this instead?

```python
scheduler.add_job("job_get_machine_status", trigger="interval", seconds=3)
```
