### ISSUE TITLE
apscheduler.schedulers.SchedulerAlreadyRunningError: Scheduler is already running

### ISSUE THREAD

**Issue by jiawei123** [viniciuschiele/flask-apscheduler#125]
when i run flask-apscheduler in cmd, it report error SchedulerAlreadyRunningError, I try to edit my scheduler's id, but is doesn't work.
If you can help me, I thanks you

**Comment by viniciuschiele** [comment]
Sorry for the delay, can you provide an example that doesn't work?

**Comment by ExperimentalHypothesis** [comment]
i have the same problem, writing API microservise and I use this scheduler to call another API every X minutes. it works but when i call an endpoint in my API i tells me apscheduler.schedulers.SchedulerAlreadyRunningError: Scheduler is already running

what is the problem and how to solve it?

**Comment by mvirnoche** [comment]
I do something like the following to get scheduler status
```python
def scheduler_running(self) -> bool:
        logger.log_message("Getting Running Status of Scheduler", module=self.module, state=self.executing)
        self.status = "Running" if self.scheduler.running else "Not Running"
        return True if self.status == "Running" else False
```
