### ISSUE TITLE
TypeError: can't pickle LockType objects

### ISSUE THREAD

**Issue by zhongyongbin1** [viniciuschiele/flask-apscheduler#128]
I want to set：  `SCHEDULER_JOBSTORES = {
    'default':
    MongoDBJobStore(database='change',
                    collection='jobs',
                    host='mongo',
                    port=27017)
}`
There was a bug：  
`api_1    | [2020-01-10 17:28:30]    ERROR: [changelogs.py:214] [MainProcess:12 DummyThread-1] - Traceback (most recent call last):   
api_1    |   File "/home/data/code/controllers/changelogs.py", line 211, in send_notify_msg   
api_1    |     replace_existing=True   
api_1    |   File "/usr/local/lib/python3.7/site-packages/flask_apscheduler/scheduler.py", line 160, in add_job   
api_1    |     return self._scheduler.add_job(**job_def)   
api_1    |   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 443, in add_job   
api_1    |     self._real_add_job(job, jobstore, replace_existing)    
api_1    |   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 867, in _real_add_job    
api_1    |     store.add_job(job)   
api_1    |   File "/usr/local/lib/python3.7/site-packages/apscheduler/jobstores/mongodb.py", line 89, in add_job   
api_1    |     'job_state': Binary(pickle.dumps(job.__getstate__(), self.pickle_protocol))   
api_1    | TypeError: can't pickle LockType objects   
api_1    |   
api_1    | [2020-01-10 17:28:30]     INFO: [changelogs.py:215] [MainProcess:12 DummyThread-1] - can't pickle LockType objects
`

**Comment by viniciuschiele** [comment]
Can you show me the job function and its parameters?

**Comment by zhongyongbin1** [comment]
I have solved this problem, but I have a new one. I wrote (func=xxx)xxxx into the class A. It seems that it can't serialize the object, which will result in locked. I put xxx in utils.py, and there's another bug:RuntimeError: Working outside of application context.Thanks
