### ISSUE TITLE
How do i use threading.Lock in jobs?

### ISSUE THREAD

**Issue by githubcyc** [viniciuschiele/flask-apscheduler#130]
i have several jobs like followings, but it can not pass `lock` as args to `add_job` fucntion.
```
lock = threading.Lock()
# only one job can get the lock 
scheduler.add_job(job1, ...)
scheduler.add_job(job2, ...)
scheduler.add_job(job3, ...)
...
```

**Comment by viniciuschiele** [comment]
you can't pass a lock object as an argument to the jobs because it needs to be serializable.
You could import the lock object from another file like:

```python
from . import lock

def job1():
    lock.acquire()
```
