### ISSUE TITLE
Interval runs only once

### ISSUE THREAD

**Issue by denisvitez** [viniciuschiele/flask-apscheduler#131]
Hi,

I just started using the flask-apscheduler and created my first job from the tutorial. The problem that I'm facing now is that the job will run only once after application startup. So the job executes just fine for the first time (after the set interval), but it never executed again.

Job configuration:
`JOBS = [
        {
            'id': 'bridge_service',
            'func': 'application.main.jobs:bridge_job',
            'args': (),
            'trigger': 'interval',
            'seconds': 1
        }
    ]
    SCHEDULER_API_ENABLED = True`

I am starting the job as such:
`if not flask_app.debug or os.environ.get('WERKZEUG_RUN_MAIN') == 'true':
        scheduler = APScheduler()
        scheduler.init_app(flask_app)
        scheduler.start()`

Before I added the IF for checking for app reload, the job executed twice, but still only once.

Anyhone has any ideas what I could be doing wrong here?

**Comment by alexisthethe** [comment]
I had exactly the same problem today.

I found a solution using [threading](https://docs.python.org/3/library/threading.html) python library and following this : https://stackoverflow.com/questions/14384739/how-can-i-add-a-background-thread-to-flask

**Comment by denisvitez** [comment]
I was in fact reading the same article, but then decided to use the second answer and the flask-apscheduler, since the implementation looked neater. But yeah, I will definitely try the threading implementation until a solution won't be found for my flask-apscheduler problem.

**Comment by viniciuschiele** [comment]
Hi, how are you hosting your service? uwsgi? gunicorn?

**Comment by denisvitez** [comment]
Hi, I am currently running it from the console with `flask manage.py run`. I haven't tried it on any wsgi servers.

**Comment by denisvitez** [comment]
I found the culprit for my strange behaviour. In my `run` command, I was running the application with `SocketIO.run(app, host='0.0.0.0')`. So if the application is started like that, it will execute the timer only for the first time. However, if I start my application by using the `manager.run()` command, the interval will work as expected. It seems that the issue is somewhat related with the SocketIO library. Any ideas why it could be like so?

**Comment by viniciuschiele** [comment]
I think that SocketIO uses asyncio, if that is the case you have to use `AsyncIOScheduler`

```python
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from flask_apscheduler import APScheduler

scheduler = APScheduler(AsyncIOScheduler())
```

**Comment by denisvitez** [comment]
Hi, I would just like to post an update to this. This still happens from time to time, but only on certain systems and when running the app from VSCode. I haven't seen the issue happen in PyCharm or somewhere else. I will close the issue :)
