### ISSUE TITLE
What difference between apscheduler and flask-apscheduler

### ISSUE THREAD

**Issue by Xelawk** [viniciuschiele/flask-apscheduler#137]
Just some confuse, I want to know if there is any exact difference between apscheduler and flask-apscheduler? Should I totaly use flask-apscheduler instead of apscheduler

**Comment by viniciuschiele** [comment]
Flask-APScheduler adds Flask endpoints to manage (add/delete/update) jobs, it is useful when you store your jobs in the database and you want to dynamically add/remove them.
If you don't need this, just use APScheduler.
