### ISSUE TITLE
Unable to modify cron expression for a job

### ISSUE THREAD

**Issue by aviweit** [viniciuschiele/flask-apscheduler#14]
Hi,

I am trying to modify a job from running every single minute, to every 10 minutes. I get "Expected a trigger instance, got unicode instead" error. I pasted below curl commands I used.

    $  curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"func": "__main__:job1", "id": "567", "name": "My job", "args": ["1", "5"], "trigger": "cron", "minute": "*/1"}' http://<service IP>:5000/scheduler/jobs

{
  "id": "567",
  "name": "My job",
  "func": "__main__:job1",
  "args": [
    "1",
    "5"
  ],
  "kwargs": {},
  "trigger": "cron",
  "minute": "*/1",
  "misfire_grace_time": 1,
  "max_instances": 1,
  "next_run_time": "2016-02-14T09:40:00+00:00"

    $ curl -v -H "Accept: application/json" -H "Content-type: application/json" -X PATCH  -d '{"trigger": "cron", "minute": "*/10"}' http://<service IP>:5000 /scheduler/jobs/567

"error_message": "Expected a trigger instance, got unicode instead"

Thanks.

**Comment by viniciuschiele** [comment]
During next week I will try to sort it out,  it is not so easy because APSchduler expects a TriggerBase instance in the trigger parameter when the job is updated.

For now a workaround you could do is removing and adding the job again.

**Comment by viniciuschiele** [comment]
I just released a new version.

Let me know if you find any other issue.

**Comment by aviweit** [comment]
Thanks. It seems that next_run_time does not get updated on start_date changes. It seems that next_run_time should be starting from at least start_date (i.e 2017-12-21)

    curl -v H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"func": "__main__:job1", "id": "4444", "name": "My job", "args": ["1", "5"], "trigger": "cron", "minute": "*/1", "start_date": "2017-12-19"}' http://<service IP>:5000/scheduler/jobs

{
  "id": "4444",
  "name": "My job",
  "func": "__main__:job1",
  "args": [
    "1",
    "5"
  ],
  "kwargs": {},
  "trigger": "cron",
  "start_date": "2017-12-19T00:00:00+00:00",
  "minute": "*/1",
  "misfire_grace_time": 1,
  "max_instances": 1,
  "next_run_time": "2017-12-19T00:00:00+00:00"
}


    curl -v -H "Accept: application/json" -H "Content-type: application/json" -X PATCH  -d '{"trigger": "cron", "minute": "*/13", "start_date": "2017-12-21"}' http://<service IP>:5000/scheduler/jobs/4444
{
  "id": "4444",
  "name": "My job",
  "func": "__main__:job1",
  "args": [
    "1",
    "5"
  ],
  "kwargs": {},
  "trigger": "cron",
  "start_date": "2017-12-21T00:00:00+00:00",
  "minute": "*/13",
  "misfire_grace_time": 1,
  "max_instances": 1,
  "next_run_time": "2017-12-19T00:00:00+00:00"
}


    curl -v -X  GET http://<service IP>:5000/scheduler/jobs/4444
{
  "id": "4444",
  "name": "My job",
  "func": "__main__:job1",
  "args": [
    "1",
    "5"
  ],
  "kwargs": {},
  "trigger": "cron",
  "start_date": "2017-12-21T00:00:00+00:00",
  "minute": "*/13",
  "misfire_grace_time": 1,
  "max_instances": 1,
  "next_run_time": "2017-12-19T00:00:00+00:00"
}

**Comment by viniciuschiele** [comment]
Good catch.

It seems APScheduler doesn't calculate the next run time when a job is updated, I will have to do it manually.
I will release a new version soon.

**Comment by viniciuschiele** [comment]
It's done, version 1.3.7

Let me know if you find any other issue.
