### ISSUE TITLE
Setting debug mode to "True" in Flask and using 'scheduler.add_job()' makes the job always is pending

### ISSUE THREAD

**Issue by Gkirito** [viniciuschiele/flask-apscheduler#148]
#140
 I find this PR makes APScheduler not start when the current process is werkzeug reloader, but it will cause a problem that when I use 'scheduler.add_job()' anywhere else like route function, the job always is pending, because the APScheduler was not started.

I suggest APScheduler should start when the current process is werkzeug reloader, but not start when the current process is not werkzeug reloader

**Comment by Gkirito** [comment]
#149

**Comment by viniciuschiele** [comment]
Hello,

I've reverted #140 as it seems to be causing issues for more users, version 1.12.1 should just work fine.

Your PR won't work when you debug your app locally, I will dig into that to find out a better solution.

Thanks

**Comment by Gkirito** [comment]
Thanks，I will test again

**Comment by Gkirito** [comment]
hello,
I've a new idea that add 'app.debug' judgment
#151

**Comment by Gkirito** [comment]
According to [flask document](https://flask.palletsprojects.com/en/1.1.x/config/#config-dev-prod)
> The ENV and DEBUG config values are special because they may behave inconsistently if changed after the app has begun setting up. In order to set the environment and debug mode reliably, Flask uses environment variables.
> The environment is used to indicate to Flask, extensions, and other programs, like Sentry, what context Flask is running in. It is controlled with the FLASK_ENV environment variable and defaults to production.
> Setting FLASK_ENV to development will enable debug mode. flask run will use the interactive debugger and reloader by default in debug mode. To control this separately from the environment, use the FLASK_DEBUG flag.
> Changelog
> Changed in version 1.0: Added FLASK_ENV to control the environment separately from debug mode. The development environment enables debug mode.

> Using the environment variables as described above is recommended. While it is possible to set ENV and DEBUG in your config or code, this is strongly discouraged. They can’t be read early by the flask command, and some systems or extensions may have already configured themselves based on a previous value.

It can be concluded that we judge debug mode by 'FLASK_DEBUG' and 'FLASK_ENV' from environment, Therefore I change 'app.debug' to 'FLASK_DEBUG' and 'FLASK_ENV'.
