### ISSUE TITLE
About APScheduler & logging

### ISSUE THREAD

**Issue by JASON0916** [viniciuschiele/flask-apscheduler#15]
Hello, since the APScheduler uses python logging module which needs to be initialized(which leads to error like [this](http://stackoverflow.com/questions/17528363/no-handlers-could-be-found-for-logger-apscheduler-scheduler) do you have a plan to reorganize the Flask logger with APScheduler?

**Comment by viniciuschiele** [comment]
Sorry, I didn't get your point.

I think this issue was already opened and explained here: https://github.com/viniciuschiele/flask-apscheduler/issues/11

Let me know if it doesn't solve your question.

**Comment by JASON0916** [comment]
Oh that really solve my problem, i just thought that may be a more general way to solve that problem instead of `logging.basicConfig()`, and your solution
```
logger = logging.getLogger()  # this returns the root logger 
logger.addHandler(logging.StreamHandler())
 ```
is much better, thank you!

**Comment by viniciuschiele** [comment]
I personally prefer to call **basicConfig()** but it is up to you.
