### ISSUE TITLE
CORS for built-in API methods

### ISSUE THREAD

**Issue by 6peterlu** [viniciuschiele/flask-apscheduler#153]
Hello! Thanks for this great package. I have a pretty basic question: How do I access the built-in APIs with CORS? I'm trying to hit my flask server, which is running on localhost, with a webclient also running on localhost, but I keep getting CORS errors.

Thanks so much!

**Comment by viniciuschiele** [comment]
You could try [Flask-CORS](https://flask-cors.readthedocs.io/en/latest) in your flask server to allow requests from different hosts

**Comment by 6peterlu** [comment]
Thanks, that helped! I realized I actually was getting the appropriate response back, but wasn't parsing it correctly.
