### ISSUE TITLE
Example for Flask with using blueprint

### ISSUE THREAD

**Issue by zak427zak** [viniciuschiele/flask-apscheduler#157]
Hello everyone!

I just can't set up the module. 
I use Flask with blueprints. Are there any examples of what to add to which file? I will be grateful!

**Comment by viniciuschiele** [comment]
Hi,

This is an example using a blueprint: https://github.com/viniciuschiele/flask-apscheduler/tree/master/examples/application_factory

**Comment by christopherpickering** [comment]
@zak427zak did you get it working?
