### ISSUE TITLE
RuntimeError: working outside of application context

### ISSUE THREAD

**Issue by ddurieux** [viniciuschiele/flask-apscheduler#16]
With flask, I use mongo database and my scheduler job use this mongo, but i have error
```
RuntimeError: working outside of application context
```

When I use call function, I use 
```
with app.test_request_context():
    functionxxx()
```

But here not possible to works. 
Do you know how to fix this problem?

**Comment by viniciuschiele** [comment]
I think you should use with `with app.app_context():`

Is this code a unit test? If so, why do you need a Flask App?

Could you provide me a full example?

Thanks!

**Comment by ddurieux** [comment]
I have found a solution, so I think we can close this ;)

**Comment by jcxmej** [comment]
@ddurieux would have been helpful if you could have shared your solution before closing the issue.. thanks.

**Comment by vijay-axis** [comment]
@ddurieux please share the solution. Thank you

**Comment by ddurieux** [comment]
Yep, sorry for the delay, 

I add jobs in config and load the config by eve: https://github.com/Alignak-monitoring-contrib/alignak-backend/blob/develop/alignak_backend/app.py#L1829-L1874

I have a file with the scheduler functions: https://github.com/Alignak-monitoring-contrib/alignak-backend/blob/develop/alignak_backend/scheduler.py

**Comment by vijay-axis** [comment]
@ddurieux Thank you

**Comment by Guibod** [comment]
This was not really helpful, let me explain it my way:

You should expose your APP as variable in one of your application module. For instance, in your `app.py` you don't expose a `create_app()` but a live app instance instead.

Then you do a local import of this application in your scheduled function:
```
def job1():
    from mylib.app import app
    app.logger.error('FUFU!')
```

At the moment i try to understand if it is not better to call `with app.application_context():`
Anyway this solution is simple.

**Comment by caio-vinicius** [comment]
I was using request.post, request.put instead of request**s**.post, request**s**.put.
