### ISSUE TITLE
Unexpected behavior when using app factory function and defining jobstores in config

### ISSUE THREAD

**Issue by caffeinatedMike** [viniciuschiele/flask-apscheduler#160]
When using the app factory pattern for my flask app I'm seeing unexpected behavior when trying to use flask_apscheduler. I utilize

I'm using an app factory function like below:
```python3
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_apscheduler import APScheduler


db = SQLAlchemy()
scheduler = APScheduler()


def create_app(config_obj='config.DevelopmentConfig'):
    app = Flask(__name__)
    app.config.from_object(config_obj)
    
    # Initialize APScheduler integration
    scheduler.init_app(app)  # attempt 1
    
    # Setup database components
    db.init_app(app)
    with app.app_context():
        from app import models
        # create db models
        db.create_all()
        # tried to start scheduler inside app_context in order for apscheduler to add the jobs table to the existing db engine, but does not work without 
        scheduler.start()  # attempt 1
        # import routes
        from app import views

    # also tried to start the scheduler outside of app_context, after db has been created and instantiated
    scheduler.init_app(app)  # attempt 2
    scheduler.start()  # attempt 2

    return app
```
And my config file looks like this:
```python3
class DevelopmentConfig(object):
    ENV = 'development'
    TESTING = True
    SECRET_KEY = 'testing'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'
    SCHEDULER_JOBSTORES = {
        'apscheduler.jobstores.default': {
            'type': 'sqlalchemy',
            'url': SQLALCHEMY_DATABASE_URI
        }
    }
```

It seems `SCHEDULER_JOBSTORES` isn't being picked up for some reason, so the only way I've been able to get it to work is by redundantly adding the jobstore inside the app factory function:
```python3
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_apscheduler import APScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore


db = SQLAlchemy()
scheduler = APScheduler()


def create_app(config_obj='config.DevelopmentConfig'):
    app = Flask(__name__)
    app.config.from_object(config_obj)
    
    # Initialize APScheduler integration
    scheduler.init_app(app)
    
    # Setup database components
    db.init_app(app)
    with app.app_context():
        from app import models
        # create db models
        db.create_all()
        # this next line should not be needed since the jobstore was already defined in config
        scheduler.scheduler.add_jobstore(SQLAlchemyJobStore(engine=db.engine, metadata=db.metadata))
        scheduler.start()
        # import routes
        from app import views

    return app
```

# Expected Behavior
Either
1. Being able to call `init_app` and `start` outside of the app_context block as long as `db.create_all()` has already been called to create the db instance
2. Being able to call `init_app` before the app_context block and calling `start` inside the app_context block, but after `db.create_all()` (since it needs to create the jobs table).

Option 2 seems the most logical and aligns with how most flask extensions operate.
The last code snippet above does work without `scheduler.scheduler.add_jobstore(SQLAlchemyJobStore(engine=db.engine, metadata=db.metadata))`, but only if `scheduler.init_app(app)` is moved *_before_* `app.config.from_object(config_obj)`, which is atypical. `init_app` should be able to be invoked after `app.config.from_object(config_obj)` since it would then be able to access the config values from the app instance.

**Comment by christopherpickering** [comment]
It seems like the problem is with ```db.create_all()```. If you remove that, and add the jobstore after the app is created, there is no problem.

Apscheduler creates its own tables, so if you are only using the db with apscheduler you can just leave out ```create_all()```

Otherwise, did you try

```python
if __name__ == "__main__":
    app.run()
    db.create_all()
    scheduler.add_jobstore(SQLAlchemyJobStore(engine=db.engine, metadata=db.metadata))
```

When you start the app you should naturally get an error as the tables haven't been created (you don't have a model specifying the tables, and apscheduler will auto create it when you add a job) - 
```bash
Error getting due jobs from job store 'apscheduler.jobstores.default': (sqlite3.OperationalError) no such table: apscheduler_jobs
```

But it will only happen once.

**Comment by caffeinatedMike** [comment]
@christopherpickering The solution you provide will not work since `app.run()` is a blocking call that runs the flask app.

And I'm using `db.create_all()` because I have other tables that need to be created. The following works, but again, it goes against the normal behavior of a flask extension.
```python3
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_apscheduler import APScheduler
from redis import Redis
import rq


db = SQLAlchemy()
bootstrap = Bootstrap()
scheduler = APScheduler()


def create_app(config_obj='config.DevelopmentConfig'):
    app = Flask(__name__)
    # Initialize APScheduler integration
    scheduler.init_app(app)  # This must be initialized before populating app config, unlike other extensions
    app.config.from_object(config_obj)
    
    # Initialize Bootstrap integration
    bootstrap.init_app(app)
    
    # Setup database components
    db.init_app(app)
    with app.app_context():
        from app import models
        # create db models
        db.create_all()
        # start the APScheduler service
        scheduler.start()
        # import routes
        from app import views

    # Initialize Redis integration
    if app.testing:
        from fakeredis import FakeStrictRedis
        app.redis = FakeStrictRedis()
    else:
        app.redis = Redis.from_url(app.config['REDIS_URL'])
    app.task_queue = rq.Queue('reporting-tasks', connection=app.redis)

    return app
```
With `config.py` containing the sqlalchemy jobstore configuration
```python3
from dotenv import load_dotenv
import os

basedir = os.path.abspath(os.path.dirname(__file__))
load_dotenv(os.path.join(basedir, '.env'))


class BaseConfig(object):
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    REDIS_URL = os.environ.get('REDIS_URL') or 'redis://'


class DevelopmentConfig(BaseConfig):
    ENV = 'development'
    TESTING = True
    SECRET_KEY = 'not-so-secret'
    SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'app.db')
    SCHEDULER_JOBSTORES = {
        'apscheduler.jobstores.default': {
            'type': 'sqlalchemy',
            'url': SQLALCHEMY_DATABASE_URI
        }
    }


class PyTestConfig(DevelopmentConfig):
    SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'
    SCHEDULER_JOBSTORES = {
        'apscheduler.jobstores.default': {
            'type': 'sqlalchemy',
            'url': SQLALCHEMY_DATABASE_URI
        }
```

**Comment by christopherpickering** [comment]
@caffeinatedMike good point, happy Monday 😂

Something else to try..

I took the code from the [application factory example](https://github.com/viniciuschiele/flask-apscheduler/tree/master/examples/application_factory), and updated the config with your jobstore like so:

```python
class DevelopmentConfig(Config):
    """Dev config."""

    DEBUG = True

    SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'
    SCHEDULER_JOBSTORES = {
        'apscheduler.jobstores.default': {
            'type': 'sqlalchemy',
            'url': SQLALCHEMY_DATABASE_URI
        }
    }
```

I changed the name from "default" to "thisone", and in the ```tasks.py``` file, I added a jobstore name on line 11:

```python

@scheduler.task(
    "interval",
    id="job_sync",
    seconds=10,
    max_instances=1,
    jobstore="thisone",
    start_date="2000-01-01 12:19:00",
)
```

then I updated the events to print the jobstore name to be sure it gets the right one. Update ```events.py```, add

```python
print(event.jobstore)
```
to the functions to see what jobstore was used.

I got the same problem as you.

So, I tried changing how the jobstore is loaded to **Method 2** in the [Apscheduler docs](https://apscheduler.readthedocs.io/en/stable/userguide.html)

like this in ```settings.py```:

```python
    SCHEDULER_JOBSTORES = {
        'thisone': SQLAlchemyJobStore(url=SQLALCHEMY_DATABASE_URI),
    }
```

( I also changed the db to ```sqlite:///test``` to get it out of memory for testing)

and the app works. The example is importing the config before declaring the app..

The output from the terminal when starting the app:
![image](https://user-images.githubusercontent.com/17788706/115257508-25212a80-a0fe-11eb-8080-ac5d4efcf592.png)

The config is still imported before the scheduler init:

```python
app.config.from_object(DevelopmentConfig)
scheduler.init_app(app)
```

Do you get the same result?
