### ISSUE TITLE
Scheduler not starting on version 1.12.2

### ISSUE THREAD

**Issue by ifokeev** [viniciuschiele/flask-apscheduler#163]
Seems like scheduler doesn't start on version 1.12.2, downgraded to 1.12.1 and started to work

**Comment by viniciuschiele** [comment]
Can you share how you are running the app? is it with gunicorn/uwsgi?

**Comment by ifokeev** [comment]
we use flask with uwsgi.

we start it like this: 
```
        @app.before_first_request
        def init_scheduler():
            from . import scheduled_tasks
            scheduler.start()
```

**Comment by viniciuschiele** [comment]
Thanks, I will do some tests

**Comment by viniciuschiele** [comment]
I couldn't reproduce this issue using `@app.before_first_request` to start the scheduler, would you be able to share a small project where this issue happens.

This is how I'm running my test app 
`uwsgi --socket 0.0.0.0:5000 --protocol=http --enable-threads -w test:app`

**Comment by ifokeev** [comment]
Around same here

```
CMD uwsgi --master \
  --py-autoreload=$AUTORELOAD \
  --wsgi-file wsgi.py \
  --callable app \
  --workers $WORKERS \
  --threads $THREADS \
  --protocol http \
  -b 32768 \
  --socket 0.0.0.0:$PORT_APP
```

I've got some stacked bugs, maybe some versions conflict. Will investigate
