### ISSUE TITLE
How to solve the problem of repeated execution of flask-apscheduler in k8s?

### ISSUE THREAD

**Issue by SongweiCao** [viniciuschiele/flask-apscheduler#169]
Is there any solution to the repeated execution of tasks created by flask-apscheduler in k8s?

**Comment by christopherpickering** [comment]
It is important not to share a jobstore between instances or a job will potentially be run multiple times. What is your configuration details? How are you running it?

**Comment by SongweiCao** [comment]
> 重要的是不要在实例之间共享作业存储，否则作业可能会多次运行。你的配置细节是什么？你如何运行它？

Only one instance is created. The instance is started by multi process, and redis is used for persistent storage. Now the task is repeated every time you start the instance Flask-Apscheduler.

**Comment by SongweiCao** [comment]
> 重要的是不要在实例之间共享作业存储，否则作业可能会多次运行。你的配置细节是什么？你如何运行它？

**Comment by billzhaox** [comment]
> > 重要的是不要在实例之间共享作业存储，否则作业可能会多次运行。你的配置细节是什么？你如何运行它？
> 
> Only one instance is created. The instance is started by multi process, and redis is used for persistent storage. Now the task is repeated every time you start the instance Flask-Apscheduler.

Hi, same issue here, did you solve the problem?
