### ISSUE TITLE
The database connection memory was not released when the job completed

### ISSUE THREAD

**Issue by chen-ABC** [viniciuschiele/flask-apscheduler#170]
job config
```
   {
            'id': 'create_prometheus_metrics_30',  # 任务id
            'func': create_prometheus_metrics,  # 任务执行程序
            'args': [],  # 执行程序参数
            'trigger': 'cron',  # 任务执行类型，定时器
            'second': '0/30',  # 任务执行时间，单位秒
        },
```
job demo:
```
def create_prometheus_metrics():
    with scheduler.app.app_context():
        from superset.models.slice import Slice
        from superset import db
        slices = db.session.query(Slice).all()
```
Memory is growing all the time

![image](https://user-images.githubusercontent.com/30097790/121684863-da1a0700-caf1-11eb-9feb-f318e7e8ee8a.png)

**Comment by christopherpickering** [comment]
@chen-ABC where do you see that the memory is increasing? 

What is in the table you query? I suppose since it is prometheus that you are querying a constantly growing data set?

**Comment by chen-ABC** [comment]
@christopherpickering    
The database data is immutable, len always 24.
i use  memory_profile 
![image](https://user-images.githubusercontent.com/30097790/121767735-d091ad00-cb8c-11eb-9100-54bbd5a3305f.png)
![image](https://user-images.githubusercontent.com/30097790/121767782-236b6480-cb8d-11eb-8730-01d859ed978c.png)
```
@profile
def create_prometheus_metrics(start_time: int, end_time: int):
    with scheduler.app.app_context():

        from superset.models.slice import Slice
        from superset import db

        slices = db.session.query(Slice).all()
        print(len(slices))
        del slices
        gc.collect()
```

**Comment by christopherpickering** [comment]
Can you try to trace it back further? Does the same thing happen if have a simple ```print("hi")``` and how sqlalchemy in the function?

What if you call the function three times without apscheduler, does the same pattern happen?

I'm interested to see why it happens, I'm running hundreds of jobs on dozens of schedules, with months between reboots, and haven't seen any memory issues.

**Comment by Bryant-Yang** [comment]
Have the same problem in my interval task with default config (BackgroundScheduler, ThreadPoolExecutor), which has sqlalchemy db operation and http requests via requests.
My flask app is running via uwsgi, memory usage doubles in two days. 
I'm trying to give a simplest test case.

**Comment by christopherpickering** [comment]
@Bryant-Yang running `htop` or something similar on your server, is the mem usage coming from your wsgi+python  processes or something else?

**Comment by Bryant-Yang** [comment]
> @Bryant-Yang running `htop` or something similar on your server, is the mem usage coming from your wsgi+python processes or something else?

My problem turned out to be caused by something else, with the help of tracemalloc.
