### ISSUE TITLE
The flask-apscheduler task is missing

### ISSUE THREAD

**Issue by SongweiCao** [viniciuschiele/flask-apscheduler#172]
Use flask-apscheduler to create a timing task. The database for storing the timing task is redis. If the timing task runs for a period of time, the ID of the timing task will be automatically deleted, which leads to the failure of the timing task. How to solve this problem?

**Comment by viniciuschiele** [comment]
I don't think this is related to flask-apscheduler, you are better asking this question in https://github.com/agronholm/apscheduler which is used by flask-apscheduler

**Comment by SongweiCao** [comment]
> 我不认为这与flask-apscheduler有关，您最好在flask-apscheduler使用的[https://github.com/agronholm/apscheduler中](https://github.com/agronholm/apscheduler)提出这个问题

Well, thank you！
