### ISSUE TITLE
How to add new task with new python script

### ISSUE THREAD

**Issue by vinayaksable2399** [viniciuschiele/flask-apscheduler#174]
I need to add totally new task with task process mentioned in new python script which not loaded star time in app
How can I add this

**Comment by christopherpickering** [comment]
Hi, what did you try so far? Did the [examples](https://github.com/viniciuschiele/flask-apscheduler/tree/master/examples) work for you?

**Comment by vinayaksable2399** [comment]
I resolved my issue
