### ISSUE TITLE
[feature request] Return jobs with specific key (/scheduler/jobs)

### ISSUE THREAD

**Issue by vlad-outscraper** [viniciuschiele/flask-apscheduler#178]
Hi, we are considering moving our production to apscheduler. Is it possible to add some kind of key to each job so when you return jobs (/scheduler/jobs or scheduler.get_jobs()) you can return only the jobs with this key?

Use case: we want to allow our users to schedule tasks so each user will store its own tasks.

**Comment by christopherpickering** [comment]
@vlad-outscraper setting the job id or name with a prefix (or something) you can identify is probably the best bet. However the jobs are pretty transient.. they leave when they are completed for example. One idea is to have your own database table that maps users > their jobs > apscheduler's job id. [This demo scheduling site](https://demo.extract.management/task/mine) does something similar - users schedule their own jobs, and the jobs show in task lists for the users.
