### ISSUE TITLE
[Feature][API] scheduler start, shutdown, pause, resume 

### ISSUE THREAD

**Issue by mxdev88** [viniciuschiele/flask-apscheduler#179]
While it's possible to pause, resume, run an individual job through the API, it's not possible to modify the state of the sheduler itself. Would it be possible to add similar endoints for the scheduler?

For example:

- /scheduler/pause [POST] > pauses the scheduler

- /scheduler/resume [POST] > resumes the scheduler

- /scheduler/start [POST] > starts the scheduler

- /scheduler/shutdown[POST] > shutdowns the scheduler

thanks for the good work!

**Comment by viniciuschiele** [comment]
That sounds good to me, I will add them later this week.
