### ISSUE TITLE
Scheduler not running when Flask running with Supervisor

### ISSUE THREAD

**Issue by ray0x44** [viniciuschiele/flask-apscheduler#184]
When running Flask app with `python app.py` directly the scheduler is working correct, jobs are scheduled and running correct too, and the scheduler status using API `curl -X GET localhost/scheduler` shows `"running": true`.

But when i run Flask app with [Supervisor](http://supervisord.org/), scheduler status API shows `"running": false` and jobs are not running any more, i tried setting `daemon=False`(`scheduler = APScheduler(scheduler=BackgroundScheduler(daemon=False))`) but seems not working, how to slove this?

**Comment by christopherpickering** [comment]
Are you running with debug=True?
