### ISSUE TITLE
Full listing of config values that flask-apscheduler accepts

### ISSUE THREAD

**Issue by kyle-tc** [viniciuschiele/flask-apscheduler#188]
These config values: https://github.com/viniciuschiele/flask-apscheduler/blob/af6f32f35998478c16b0a876e917966c52de1fe4/flask_apscheduler/scheduler.py#L294-L323

Could be listed here: https://viniciuschiele.github.io/flask-apscheduler/rst/configuration.html

I think it's less confusing if they just get listed there, as opposed to having to dig in the apscheduler link. I found myself having to go back to the code link above to check what values I should use anyways.

**Comment by viniciuschiele** [comment]
Hi,

I added the list of configurations to the docs without adding many details, feel free to push a PR to improve it.
I have no intention to copy the documentation that is already in APScheduler's documentation into this project.

**Comment by kyle-tc** [comment]
Thanks @viniciuschiele just having them listed is helpful enough IMO.
