### ISSUE TITLE
Integrate generated /scheduler endpoint with flask-restplus's swagger UI

### ISSUE THREAD

**Issue by bedge** [viniciuschiele/flask-apscheduler#19]
We're using flask-restplus to generate a testing UI that allows QA/developers to browse the API interactively. It generated test pages & documentation for all appropriately annotated endpoints.
Currently the /scheduler EP is basically "hidden" as it does not expose the same flask-restplus metadata.
If this were added, then it would show up in the generated swagger-ui and one could see/browse the EP without knowing of it;s existence and path in advance.

**Comment by viniciuschiele** [comment]
I would need to add a dependency to flask-restplus to implement this feature and this is something that I wouldn't like.

A workaround would be to override the class `Swagger` from flask-restplus to add those endpoints from APScheduler.

e.g:
`api._schema = MySwagger()`

**Comment by bedge** [comment]
fair enough. will investigate & report back, thanks.

**Comment by wbarnha** [comment]
Was this ever investigated again? It'd be nice to have some Swagger docs.
