### ISSUE TITLE
Error: Failed to find Flask application or factory in module "flaskr.test.test". Use "FLASK_APP=flaskr.test.test:name to specify one.

### ISSUE THREAD

**Issue by code-yuan-shi** [viniciuschiele/flask-apscheduler#190]
hi! I just follow your example named jobs and it generate error like Title，my Flask version is 1.1.2 and Flask-APScheduler is 1.12.2, I'm looking forward to your help, thanks

**Comment by christopherpickering** [comment]
Hi,
How did you run the app? It looks like you may have spelled `flask` wrong? (`flaskr`)?

You can run it directly with `python jobs.py`.

```sh
➜  examples git:(master) python jobs.py                                                     
 * Serving Flask app "jobs" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 167-811-474
1 2
1 2
1 2
1 2
```

**Comment by code-yuan-shi** [comment]
> Hi, How did you run the app? It looks like you may have spelled `flask` wrong? (`flaskr`)?
> 
> You can run it directly with `python jobs.py`.
> 
> ```shell
> ➜  examples git:(master) python jobs.py                                                     
>  * Serving Flask app "jobs" (lazy loading)
>  * Environment: development
>  * Debug mode: on
>  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
>  * Restarting with stat
>  * Debugger is active!
>  * Debugger PIN: 167-811-474
> 1 2
> 1 2
> 1 2
> 1 2
> ```

Thanks for your reply, I was running at pycharm,` flaskr` just my file name, in this path, I create other flask app and it can work normally, I don't know if my python version is too high?(python 3.7), What else could be the problem?

**Comment by christopherpickering** [comment]
Can you share your file structure and the command you used to launch it?
From the error message, you have a folder ``flaskr/test/test/`` and the ``jobs.py`` is inside the last `test` folder?

What did you set ``FLASK_APP=`` to?

**Comment by code-yuan-shi** [comment]
Good morning！（in my time zone), first of all thank you very much for your help, I realize why I meet this error. On the one hand, You can't just click on the run main function in pycharm but use `python jobs.py` in shell, on the other hand, for value of key func designated file name must be jobs.py but at first I create a test.py.

**Comment by Shank0071** [comment]
Hi! If you get this error, then make sure you have 'saved the file' in the text editor and rerun the app.
