### ISSUE TITLE
scheduler.get_jobs() output to json format

### ISSUE THREAD

**Issue by TCP-88** [viniciuschiele/flask-apscheduler#193]
Hi can i get this scheduler.get_jobs() output to json format?

**Comment by viniciuschiele** [comment]
If you want an endpoint that returns the jobs in JSON format, you can use this endpoint: https://github.com/viniciuschiele/flask-apscheduler/blob/master/flask_apscheduler/scheduler.py#L345

If you want to manually serialize the jobs in JSON, you can check this method: https://github.com/viniciuschiele/flask-apscheduler/blob/master/flask_apscheduler/api.py#L82

**Comment by TCP-88** [comment]
Hi @viniciuschiele 

Thanks for reply, so sorry im so new to python :) , when i try to get  api.geet_jobs but it only show me below.

<Response 82 bytes [200 OK]>

**Comment by viniciuschiele** [comment]
I didn't run this code but it should work:

```python
import json

from flask_apscheduler import APScheduler

scheduler = APScheduler()

...

var jobs = apscheduler.get_jobs()

var jobsAsJson = json.dumps(jobs)
```

**Comment by TCP-88** [comment]
Thanks, i have found this 
```
    for job in scheduler.get_jobs():
        jobdict = {}
        for f in job.trigger.fields:
            curval = str(f)
            jobdict[f.name] = curval
        cron.append(jobdict)
```
