### ISSUE TITLE
The docs are not available

### ISSUE THREAD

**Issue by nick-maykr** [viniciuschiele/flask-apscheduler#194]
Hi! Thanks for this simple and amazing app.

Unfortunately the previously available documentation at https://viniciuschiele.github.io/flask-apscheduler/index.html
now returns 404. 
Could you fix it, please?

<img width="2012" alt="Screenshot 2021-12-15 at 10 00 06" src="https://user-images.githubusercontent.com/75306162/146138813-4a55c896-1c8e-45d7-bf9c-a4e87b56788f.png">
?

**Comment by viniciuschiele** [comment]
@christopherpickering would you know why the documentation page isn't being generated?

**Comment by christopherpickering** [comment]
It looks like the docs branch is blank, I'll check it out!

**Comment by christopherpickering** [comment]
Ah I see, its trying to build the docs on py37, which isn't installed in the action. I'll do a pr to fix it.

**Comment by christopherpickering** [comment]
I think #195 should fix it.

**Comment by viniciuschiele** [comment]
I've merged #195, the docs branch is populated now, but I'm still seeing 404 for https://viniciuschiele.github.io/flask-apscheduler
Have any clue?

**Comment by christopherpickering** [comment]
Its working for me now, I guess it takes some time, or clear your cache?


Dec 15, 2021, 4:46 PM by ***@***.***:

**Comment by viniciuschiele** [comment]
It's working now, thanks for your help with this.

**Comment by christopherpickering** [comment]
Thank you!

Dec 15, 2021, 6:06 PM by ***@***.***:
