### ISSUE TITLE
How can I modify the job properties after starting?

### ISSUE THREAD

**Issue by piejanssens** [viniciuschiele/flask-apscheduler#2]
https://apscheduler.readthedocs.org/en/latest/userguide.html#modifying-jobs

I want to change the interval while it's scheduled.
In general how can I access the 'job' object?

**Comment by viniciuschiele** [comment]
Hi,

You could get the native apscheduler object to reschedule/modify your job.

```python
sched = APScheduler()
scheduler = sched.scheduler # it returns the native apscheduler instance
scheduler.reschedule_job('my_job_id', trigger='cron', minute='*/5')
```
I will write next week new functions in my APScheduler class to modify the jobs.
 
Cheers!

**Comment by piejanssens** [comment]
Thanks man! It works great (after the gevent monkey patch) :smile:
