### ISSUE TITLE
Right way to enable job "one at a time" job thread execution.

### ISSUE THREAD

**Issue by bedge** [viniciuschiele/flask-apscheduler#20]
I want to ensure that another job thread is not started if one is still running.
This is useful for debugging so that you don't get jobs piled up if you hit a break point.

I was considering following the example and using:
```python
    SCHEDULER_EXECUTORS = {
        'default': {'type': 'threadpool', 'max_workers': 1}
}
```
But I wasn't sure if that was the best option.

I also saw this is the example, but I'm not clear on what exactly this does:
```python
    SCHEDULER_JOB_DEFAULTS = {
        'coalesce': False,
        'max_instances': 3
}
```

**Comment by viniciuschiele** [comment]
Hi @bedge 

The SCHEDULER_JOB_DEFAULTS configuration is per job, that means each job can execute at most 3 threads at the same time.

The SCHEDULER_EXECUTORS is a global configuration, in this case, only 1 thread will be used for all the jobs.

I believe the best way for you is to use max_workers: 1 when running locally

**Comment by bedge** [comment]
perfect! thanks.
