### ISSUE TITLE
Problems with scheduler by cron

### ISSUE THREAD

**Issue by mgmmgg** [viniciuschiele/flask-apscheduler#201]
Hi.
I have some problem with scheduler by cron. I use Flask with blueprints. The task is started by cron, but it is duplicated (the same task is started twice at the same time. I see it in logs). 
Then i downloaded your example with blueprints and launched it. The same mistake was there too. 
Can you help me to decide this problem?
Thank you

**Comment by viniciuschiele** [comment]
Hi,

I think it is the same as https://github.com/viniciuschiele/flask-apscheduler/issues/139

How are you running your app? Is it locally? gunicorn?

**Comment by mgmmgg** [comment]
Ok, thank you, it is the same problem. 



Отправлено из мобильной Почты Mail.ru


воскресенье, 20 марта 2022 г., 15:03 +0300 от ***@***.***  ***@***.***>:
