### ISSUE TITLE
Flask-APScheduler not running when running in executable version by PyInstaller

### ISSUE THREAD

**Issue by zaingithub** [viniciuschiele/flask-apscheduler#205]
hello, i am using flask-apscheduler to my software then bundled to exe by pyinstaller.

The scheduler API show my future job that i added by flask apscheduler.

but until passed the next run time of my job, the job is not running, and the scheduler api still same (no any changes).

The scheduler running well before it bundled to exe file.

Can you help me please?

**Comment by zaingithub** [comment]
i can not see any error log due to this

**Comment by christopherpickering** [comment]
@zaingithub were you able to resolve this? If not can you share a code example? How were you calling the scheduler in your exe? Closing until more information is available.
