### ISSUE TITLE
Scheduling/synchronization options.

### ISSUE THREAD

**Issue by bedge** [viniciuschiele/flask-apscheduler#21]
Is there any recommended configuration for process synchronization between flask request handler threads/processes & APScheduler threads.

This gets more complicated with running under gunicorn.

Is there a preferred worker class to use with flask/flask-apscheduler, ie: sync, gevent, etc?
http://docs.gunicorn.org/en/latest/settings.html#worker-class

**Comment by viniciuschiele** [comment]
By default, APScheduler runs all jobs in a separated thread so it does not really matter which worker class you are going to use.

The worker will handle only the HTTP calls to Flask so I would say to use the worker that usually you use for other web apps.
