### ISSUE TITLE
Not able to run the cron job in the background of api on Flask

### ISSUE THREAD

**Issue by ghulamyazdani** [viniciuschiele/flask-apscheduler#213]
![image](https://user-images.githubusercontent.com/55938346/190091212-8a5b07f3-2c84-40d2-814d-653a5c50364f.png)

Getting scheduler already running issue while hitting an endpoint on my flask api which also has cron jobs with flask-apscheduler.

Cron job that I have - 
![image](https://user-images.githubusercontent.com/55938346/190091770-b53f1c26-702f-43f9-8d55-a510644f0441.png)

api endpoint - 
![image](https://user-images.githubusercontent.com/55938346/190091923-cf9ff1d2-2863-44b7-b1aa-4882977cbd4e.png)

**Comment by christopherpickering** [comment]
hi! How did you start the scheduler? In you api endpoint, how are you calling the scheduler again?

**Comment by ghulamyazdani** [comment]
I am starting it in __init__.py
![image](https://user-images.githubusercontent.com/55938346/190103471-9134d3cb-ed3a-424d-9a41-e2215f559eba.png)

**Comment by christopherpickering** [comment]
Do you have your code on github somewhere? 
Try using this [example](https://github.com/viniciuschiele/flask-apscheduler/blob/master/examples/advanced.py).

**Comment by Huyueeer** [comment]
+1 I had the same problem

**Comment by christopherpickering** [comment]
Probably! If you have a reproducible example to share it would help... I can't produce the error with the examples.

**Comment by Huyueeer** [comment]
I solved this problem by:
- Configuring in a virtual environment （Modify deployment parameters as appropriate）
  - `export FLASK_APP=flaskr`
  - `export FLASK_ENV=development`
- Then execute the command and return to normal
  - `gunicorn main:app --preload`

**Comment by christopherpickering** [comment]
Ah yeah, the scheduler must run in a single worker process. Alternatively you can run `gunicorn  --workers 1 main:app` in production. https://viniciuschiele.github.io/flask-apscheduler/rst/tips.html
