### ISSUE TITLE
Question about use the gunicorn to deploy flask-apsscheduler?

### ISSUE THREAD

**Issue by roronoaihxn** [viniciuschiele/flask-apscheduler#215]
SCHEDULER_EXECUTORS = {
        "default": {"type": "threadpool", "max_workers": 20},
        'process_executor': ProcessPoolExecutor(5),
    }

my run way:
```
gunicorn wsgi --bind 0.0.0.0:5000 --workers 1 --worker-class gevent
```

Does the process_executor or threadpool auto shutdown after i restart the gunicorn worker?

**Comment by christopherpickering** [comment]
Restarting gunicorn should also restart the threadpool... does for me :)
