### ISSUE TITLE
Trying to run a function as a schedule and also trigger on demand

### ISSUE THREAD

**Issue by securitypedant** [viniciuschiele/flask-apscheduler#219]
Hi

I am writing a simple Flask app to monitor an ISP connection. I have flask-apscheduler setup to run a speed test function every 3 hours. I also want to allow the user, via the web UX, to trigger a speed test on demand.

However i'm running into all sorts of issues.

1. I only want one speed test to be running at any time. So when the job starts, I want it to check if a manual speed test has already started. I was going to use g or session to track if the speed test is running, but I ran into a lot of issues with "RuntimeError: Working outside of application context.". I tried using "with scheduler.app.app_context():" but that didn't work.
2. Ideally I would like to get a job, determine if it's running and then if not, run a one time execution of a job. Because the default behaviour for a job is only one instance, this would be ideal. Because if I manually start a job, then the interval schedule triggers it, only one instance of that job will run.

Any ideas on the right way to do this?

**Comment by christopherpickering** [comment]
Can you give your job an id, and then check the jobstore for the id's status before running? Setting the max instances to 1 should prevent the scheduler from running the chron job at the same time as a user triggering the job.

https://apscheduler.readthedocs.io/en/3.x/userguide.html#adding-jobs

**Comment by securitypedant** [comment]
That would be a way to prevent my manual job from running. However, the piece I need to figure out is, for the manual job, I want to run an existing scheduler job on demand. So that if the scheduled job runs, it see's a job was already started... for example...

0 mins - SpeedTest runs on schedule
5 mins - SpeedTest runs on schedule
10 mins - SpeedTest runs on schedule
14 mins - SpeedTest run manually from UX
15 mins - SpeedTest runs on schedule, see's a manual start of the same job already running and therefore doesn't run.

**Comment by christopherpickering** [comment]
To run a function on demand you can submit it as a "one off" job with the current time as the start time.
https://apscheduler.readthedocs.io/en/3.x/modules/triggers/date.html#module-apscheduler.triggers.date

You will have one function that setups the cron/interval job, and one function for the one-off run.
Both will call the same function and have the same id. When the job is manually triggered, before sending it to the scheduler you could check the id. I'm not 100% sure what the max instances will do when you try to add more than one (will it queue them or just ignore it?) > you can find in the docs, it is possible that the max instances will solve all the problems.

**Comment by securitypedant** [comment]
Thanks Christopher, will try this out.
