### ISSUE TITLE
how to know whether a job has run successfully or not

### ISSUE THREAD

**Issue by rookiebulls** [viniciuschiele/flask-apscheduler#22]
If the scheduler executes a job at a certain time, how do I know this job has been executed successfully or not? without any debugging logs or anything. Is there any api that I can access it?

**Comment by viniciuschiele** [comment]
Hi @rookiebulls 

APScheduler doesn't keep the status of the last executions, you have to do it yourself using logs for instance.

You could also implement a custom `Executor` that will store/log the execution for all jobs.
