### ISSUE TITLE
Flask-APScheduler not running when set some environment variables

### ISSUE THREAD

**Issue by GodsDusk** [viniciuschiele/flask-apscheduler#220]
set FLASK_ENV=development  or  FLASK_DEBUG any value

**Comment by christopherpickering** [comment]
@GodsDusk Can you share an example?

**Comment by GodsDusk** [comment]
here is an example:

> M1 Pro Ventura
> python 3.10
> Flask-APScheduler 1.12.4 
> Flask 2.2.2
> gevent 22.10.2

```python
# run.py
from flask import Flask
from flask_apscheduler import APScheduler

scheduler = APScheduler()


@scheduler.task("interval", id="job1", seconds=3, misfire_grace_time=900)
def job1():
    """Sample job 1."""
    print("Job 1 executed")


if __name__ == "__main__":
    app = Flask(__name__)

    scheduler.init_app(app)
    scheduler.start()

    from gevent.pywsgi import WSGIServer
    http_server = WSGIServer(('0.0.0.0', 5001), app)
    http_server.serve_forever()
```

first, I exec `python run.py`, It works fine, and "Job 1 executed" is printed on the console.

Then, I exec `export FLASK_DEBUG=development && python run.py`, nothing printed

**Comment by christopherpickering** [comment]
Well, in development you can use the flask dev server, using one of these excellent examples: https://github.com/viniciuschiele/flask-apscheduler/tree/master/examples

Using a production server + debug will prevent the scheduler from starting https://github.com/viniciuschiele/flask-apscheduler/blob/bab402bac584a792eab5fa28f99135c9f6c10b12/flask_apscheduler/scheduler.py#L97

This was done to allow development to work with the flask debugger.

You could tweak your startup to look something like:

```py
from flask.helpers import get_debug_flag
if get_debug_flag():
    app.run()
else:
    .... wsgi server run forever
