### ISSUE TITLE
APScheduler not working with gunicorn eventlet

### ISSUE THREAD

**Issue by rsking01** [viniciuschiele/flask-apscheduler#225]
Hello. Faced the problem that the Flask-APScheduler jobs are not executed when the application is launched via gunicorn. Without gunicorn (with running directly through python app.py) everything works fine. I am using eventlet.

main.py:
```
from flask import Flask, render_template, url_for, redirect, request
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, login_user, login_required, \
						current_user, logout_user

from flask_xcaptcha import XCaptcha
from flask_socketio import emit

from app import app, socketio, scheduler
from apscheduler.triggers.cron import CronTrigger

import datetime

@scheduler.task(trigger=CronTrigger.from_crontab('*/5 * * * *'), id = 'job1', next_run_time=datetime.datetime.now())
def job1():
	print('ok')
```

app.py:
```
import eventlet
eventlet.monkey_patch(thread=True, time=True)

from flask import Flask
from flask_socketio import SocketIO
from flask_apscheduler import APScheduler

app = Flask('app')

app.secret_key = 'secret'
app.config['SESSION_TYPE'] = 'filesystem'
app.config['SESSION_FILE_DIR'] = './flask_session'
app.config['SOCK_SERVER_OPTIONS'] = {'ping_interval': 25, 'max_message_size': 120}

scheduler = APScheduler()
scheduler.api_enabled = True
scheduler.init_app(app)

socketio = SocketIO(app)
```

wsgi,py:
```
from main import app, socketio, scheduler

if __name__ == "__main__":
	scheduler.start()
	socketio.run(app, host = '0.0.0.0')

```

gunicorn launch options:
`gunicorn --worker-class eventlet -w 1 --bind unix:gunicorn.sock -m 007 wsgi:app`

I also want to note that the scheduler itself is initialized. I can go to /scheduler, but there I see that the parameter running = False:
`{"current_host": "aeza.network", "allowed_hosts": ["*"], "running": false}`

Also the versions of my modules:

```
APScheduler           3.10.1
backports.zoneinfo    0.2.1
bidict                0.22.1
certifi               2022.12.7
charset-normalizer    3.1.0
click                 8.1.3
dnspython             1.16.0
eventlet              0.30.2
Flask                 2.2.3
Flask-APScheduler     1.12.4
Flask-Login           0.6.2
Flask-MySQLdb         1.0.1
Flask-SocketIO        5.3.3
Flask-xCaptcha        0.5.4
greenlet              2.0.2
gunicorn              20.1.0
h11                   0.14.0
idna                  3.4
importlib-metadata    6.3.0
itsdangerous          2.1.2
Jinja2                3.1.2
loguru                0.7.0
MarkupSafe            2.1.2
mysqlclient           2.1.1
pip                   20.0.2
pkg-resources         0.0.0
PyMySQL               1.0.3
python-dateutil       2.8.2
python-engineio       4.4.0
python-socketio       5.8.0
pytz                  2023.3
pytz-deprecation-shim 0.1.0.post0
requests              2.28.2
setuptools            44.0.0
simple-websocket      0.10.0
six                   1.16.0
tzdata                2023.3
tzlocal               4.3
urllib3               1.26.15
Werkzeug              2.2.3
wheel                 0.40.0
wsproto               1.2.0
zipp                  3.15.0
zope.event            4.6
zope.interface        6.0
```

Why are tasks not being completed? What is it connected with?

**Comment by christopherpickering** [comment]
hi @rsking01 when you run the app through `app.py`, what command are you using to start it? Are you moving the scheduler.start command into the app.py?

**Comment by rsking01** [comment]
> hi @rsking01 when you run the app through `app.py`, what command are you using to start it? Are you moving the scheduler.start command into the app.py?

No, for testing, I ran wsgi.py right away on the same server, via the python command. And everything worked fine, but it's worth running through gunicorn, so the tasks are not executed. But at the same time, the scheduler API works

**Comment by viniciuschiele** [comment]
I think you are not calling `scheduler.start()` when running via gunicorn.

**Comment by rsking01** [comment]
> I think you are not calling `scheduler.start()` when running via gunicorn.

Why is this happening? After all, I call scheduler.start () before socketio.run (), but at the same time socketio is started

**Comment by christopherpickering** [comment]
@viniciuschiele is right, running like this `FLASK_DEBUG=false FLASK_APP=wsgi.py python wsgi.py` works because `__name__ == "__main__"`, but when you run with gunicorn, this is not the case.

If you add a print statement in there you will see that when calling directly with python the name is `__main__`, but when running with gunicorn the name is `wsgi`.

![image](https://user-images.githubusercontent.com/17788706/232545054-1bcc1504-3cf7-4d3d-bfb6-8529adfc0b3d.png)

![image](https://user-images.githubusercontent.com/17788706/232545128-979f5a76-9ac1-46e7-a6af-1c5b9b50307f.png)

**Comment by rsking01** [comment]
> @viniciuschiele is right, running like this `FLASK_DEBUG=false FLASK_APP=wsgi.py python wsgi.py` works because `__name__ == "__main__"`, but when you run with gunicorn, this is not the case.
> 
> If you add a print statement in there you will see that when calling directly with python the name is `__main__`, but when running with gunicorn the name is `wsgi`.
> 
> ![image](https://user-images.githubusercontent.com/17788706/232545054-1bcc1504-3cf7-4d3d-bfb6-8529adfc0b3d.png)
> 
> ![image](https://user-images.githubusercontent.com/17788706/232545128-979f5a76-9ac1-46e7-a6af-1c5b9b50307f.png)

Everything was so easy. Many thanks for the help! In addition, I want to add that launching the application in wsgi was not needed, gunicorn turns out to launch it itself, and I didn’t even know this all this time.
