### ISSUE TITLE
Flask 3.0.0 support

### ISSUE THREAD

**Issue by hongbo-miao** [viniciuschiele/flask-apscheduler#235]
Currently there is a limitation for Flask version:

https://github.com/viniciuschiele/flask-apscheduler/blob/e29d542d610b49a73d5ca1750c0ace70c3291c7d/requirements.txt#L1

It would be great to support Flast 3.0.0, thanks! ☺️

**Comment by viniciuschiele** [comment]
Version 1.31.1 is out with support for Flask 3
