### ISSUE TITLE
Duplicating Startup Jobs

### ISSUE THREAD

**Issue by rj919** [viniciuschiele/flask-apscheduler#28]
When I add jobs after flask is started (through a req to the /scheduler), it behaves correctly, but somehow I cannot seem to get apscheduler to run only one instance of a job during startup. It creates two of each job regardless of whether I have max instances set to 1.  At this point, I'm not sure this is a problem with my configuration or the code itself since this phenomena occurs whether I use gevent or not as either the flask engine or the scheduler. 
```
# construct flask app object
from flask import Flask, request, session, jsonify, url_for, render_template
app = Flask(import_name=__name__)

# initialize logging and debugging
import sys
import logging
app.logger.addHandler(logging.StreamHandler(sys.stdout))
app.logger.setLevel(logging.DEBUG)
app.config['ASSETS_DEBUG'] = False

# construct the landing page
@app.route('/')
def landing_page():
    return jsonify({'status':'ok'}), 200

# construct the catchall for URLs which do not exist
@app.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

# construct scheduler object (with gevent processor)
from flask_apscheduler import APScheduler
from apscheduler.schedulers.gevent import GeventScheduler
gevent_scheduler = GeventScheduler()
ap_scheduler = APScheduler(scheduler=gevent_scheduler)

# add job to app scheduler
from time import time
scheduler_configs = {
    'SCHEDULER_JOBS': [ {
        'id': 'app.logger.debug.%s' % str(time()),
        'func': 'launch:app.logger.debug',
        'kwargs': { 'msg': 'APScheduler has started.' },
        'misfire_grace_time': 5,
        'max_instances': 1,
        'replace_existing': False,
        'coalesce': True
    } ],
    'SCHEDULER_TIMEZONE': 'UTC',
    'SCHEDULER_VIEWS_ENABLED': True
}
app.config.update(**scheduler_configs)

# attach app to scheduler and start scheduler
ap_scheduler.init_app(app)
ap_scheduler.start()

# initialize test wsgi localhost server with default memory job store
if __name__ == '__main__':
    from gevent.pywsgi import WSGIServer
    http_server = WSGIServer(('0.0.0.0', 5001), app)
    http_server.serve_forever()
    # app.run(host='0.0.0.0', port=5001)
```

**Comment by viniciuschiele** [comment]
Hi @rj919 

I tried to run your code and it runs the job only once on startup, I added the same job through the API it will execute another time, It seems to work as expected.

Maybe I didn't understand well your question, you could rephrase it?

**Comment by rj919** [comment]
After some further investigation, it appears the phenomena is associated with calling the startup file a second time. Whenever a function references the same file that houses the app object for the first time, it re-initializes the startup jobs. So, since the startup job launch:app.logger.debug was referencing it's own file, it was duplicated along with all the other jobs added to the scheduler by commands in launch.py

This may be a feature of how Flask_APScheduler or APScheduler itself retrieves callables. But, it is definitely occurring both in my windows environment and my alpine linux virtualbox.

For most things, I think I can work around this problem by putting the callables in other files, but it may be tricky trying to incorporate the app object into other callables (for say logging) since any reference to the file with the scheduler seems to invoke it a second time.

Thoughts?

**Comment by viniciuschiele** [comment]
Now I see the issue, that isn't going to work.

You have to restructure your project, you have to instantiate Flask and APScheduler in one file and initialize them in another file.

For example: 

**__init__.py**
```python
app = Flask()
scheduler = APScheduler()
```
**jobs.py**
```python
from . import app

def job1():
    app.logger.debug('lalala')
```
**lunch.py**
```python
from . import app, scheduler

if __name__ == '__main__':
    scheduler.init_app(app)
    app.run()
```

**Comment by eayin2** [comment]
I use app.run(use_reloader=False) to prevent flask to create two instances of flask_apscheduler.APScheduler. If I omit use_reload=False jobs are also fired twice for me.

**Comment by viniciuschiele** [comment]
In his example above, even using use_reloader=False it will still happen.

Anyway, it is not a good practice to put everything into one single file.

**Comment by rj919** [comment]
Separating the init from the launch did the trick. And... you make a good point about putting all the configs into an init file being better practice (especially for all these self-referential callables). Thanks!
