### ISSUE TITLE
Add info to readme for running on top of flask-socketio

### ISSUE THREAD

**Issue by piejanssens** [viniciuschiele/flask-apscheduler#3]
I had weird results. Scheduling with a 5s interval resulted in this:

```
1437117604.32 :calling update() thread: MainProcess - Thread-10 
1437117605.6 :calling update() thread: MainProcess - Thread-14 
1437117609.35 :calling update() thread: MainProcess - Thread-10 
1437117610.62 :calling update() thread: MainProcess - Thread-14 
1437117614.32 :calling update() thread: MainProcess - Thread-13 
1437117615.61 :calling update() thread: MainProcess - Thread-17 
1437117619.32 :calling update() thread: MainProcess - Thread-10 
```

Solution is to use the monkey patch from gevent by putting this above all other imports in your app.py:
```
from gevent import monkey
monkey.patch_all()
```

**Comment by viniciuschiele** [comment]
@piejanssens

Have you tried GeventScheduler? It might solve your issue too.

The following code is just a guess, I have not tried running it.

```python
from apscheduler.schedulers.gevent import GeventScheduler
from flask_apscheduler import APScheduler

sched = APScheduler(GeventScheduler())
```

Cheers!

**Comment by piejanssens** [comment]
That's even better! The monkey patch caused this ugly thing: http://stackoverflow.com/questions/8774958/keyerror-in-module-threading-after-a-successful-py-test-run
