### ISSUE TITLE
Run job and get data from DB

### ISSUE THREAD

**Issue by erwinyusrizal** [viniciuschiele/flask-apscheduler#30]
Hi @viniciuschiele Thanks for your flask-apscheduler, it makes my life easier :D

Btw I have an issue while running the scheduler job. The job it self works perfectly until I tried to access my db model it throws error

`RuntimeError: application not registered on db instance and no application bound to current context`

any solution how to use the db instance and app context to the job views?

Thanks

**Comment by erwinyusrizal** [comment]
Ok I got it working now

**Comment by Quanr** [comment]
can you tell me how you solved it?

**Comment by erwinyusrizal** [comment]
@Quanr if you need a request context you can use 
`with scheduler.app.test_request_context():` otherwise you can use app_context `with scheduler.app.app_context():`

**Comment by Quanr** [comment]
@erwinyusrizal Thanks so much. It works!

**Comment by wck821829906** [comment]
@ “application not registered on db instance and no applicationbound to current context” also happens in my application, I confused how to solve it with "request context", could you guys help me?

**Comment by erwinyusrizal** [comment]
@wck821829906 
Use either request context 
`with scheduler.app.test_request_context():`

or

app context
`with scheduler.app.app_context():`
