### ISSUE TITLE
scheduler events feature

### ISSUE THREAD

**Issue by fitamant** [viniciuschiele/flask-apscheduler#32]
Hi,
Can you add scheduler events management in your module as the apscheduler module allows ? (https://apscheduler.readthedocs.io/en/latest/userguide.html#scheduler-events)
Thanks,
Best regards,

**Comment by viniciuschiele** [comment]
Hi @fitamant 

I've added the methods add_listener and remove_listener to the scheduler class.

https://github.com/viniciuschiele/flask-apscheduler/blob/master/flask_apscheduler/scheduler.py#L93
https://github.com/viniciuschiele/flask-apscheduler/blob/master/flask_apscheduler/scheduler.py#L108

I will soon release a new version on pypi.

Thanks

**Comment by viniciuschiele** [comment]
I just released the version 1.6.0
