### ISSUE TITLE
Are there any examples on how to use this within the flask app context? 

### ISSUE THREAD

**Issue by dhhagan** [viniciuschiele/flask-apscheduler#34]
For ex. If I wanted to run an automated task to perform some operation on a model, I seem to be continually running into context errors. Is this even possible/reasonable?

**Comment by viniciuschiele** [comment]
Hi,

I guess you are using Flask-SQLAlchemy and you want to access your model within a task, that is a small example how to create a context within a task, 

e.g:
```python
def your_task():
    with app.app_context():
        users = User.query.all()
        ...
```

I will soon add an example in the examples folder.

**Comment by dhhagan** [comment]
Yea! I am using flask-sqlalchemy. I tried more or less what you posted above, but haven't had any luck. I'm trying to use within a blueprint, which may also be causing issues.

**Comment by viniciuschiele** [comment]
Could you tell what is the error you are getting?

Have you tried to get the current app?
e.g:
```python
from flask import current_app

def your_task():
    with current_app.app_context():
        users = User.query.all()
```

**Comment by viniciuschiele** [comment]
What do you mean by within a blueprint? 
A task is not related to a blueprint, you need to have access to the original Flask app instance to create a new app context.

You can access it using ```apscheduler.app```.

e.g:
```python
scheduler = APScheduler()

def your_task():
    app = apscheduler.app
    with app.app_context():
        users = User.query.all()
```

**Comment by viniciuschiele** [comment]
I just added a new example: 
https://github.com/viniciuschiele/flask-apscheduler/blob/master/examples/flask_context.py

Let me know if it doesn't help you.

**Comment by dhhagan** [comment]
Awesome. I think I finally just got it to work. Thanks for the help.

**Comment by dhhagan** [comment]
Actually, I've been having one more issue. It seems that although everything runs great in development, in production I get an error from apscheduler that says it can't import the module.

It throws: LookupError: Error resolving reference app.utilities:backup_data_to_s3: could not import module.

Have you seen anything like this? For context, I'm using gunicorn/eventlet behind an NGINX proxy.

![screen shot 2017-02-07 at 10 39 31 am](https://cloud.githubusercontent.com/assets/4370504/22698350/4d8ea82e-ed22-11e6-8031-ded7017ed476.png)

**Comment by viniciuschiele** [comment]
Hard to tell, usually it happens when either the task path is incorrect or the module has something wrong.

The folder /var/www/tata/tata has a file __init__.py? If so, I guess your task path should be ```tata.app.utilities:daily_backup_data_to_s3```

**Comment by dhhagan** [comment]
@viniciuschiele Nope. No `__init__.py` file in that directory. There is in the `app` directory. The file structure is:

<code>
\app
    models.py
    utilities.py
    __init__.py
    \blueprint_1
config.py
manage.py
</code>

I think that's all of the relevant files...It could be that something in the module is wrong, though it works/executes fine locally..so I'm a bit confused.

**Comment by viniciuschiele** [comment]
One thing you could do is to get the full path of the task using an utility from APScheduler.

```python
from apscheduler.util import obj_to_ref
from app.utilities import daily_backup_data_to_s3

full_path = obj_to_ref(daily_backup_data_to_s3)
```

Run the above code in production, it will return the path of your task function.

Just for knowledge, my library uses the inverse method to get the function based on the path.

```python
from apscheduler.util import ref_to_obj

task_func = ref_to_obj('app.utilities:daily_backup_data_to_s3')
```

**Comment by viniciuschiele** [comment]
Hi @dhhagan 

Any luck on it?

**Comment by nextcoder** [comment]
```
scheduler = APScheduler()

def your_task():
    app = apscheduler.app
    with app.app_context():
        users = User.query.all()
```
This only works if the scheduler is defined within the same  module as the task. For any sizeable real-life application, the job most likely life in another file, how do I make the scheduler object available?

Related to that, why isn't the scheduler object available from within the task by default?

**Comment by viniciuschiele** [comment]
yeah, that is what I recommend, just define your APScheduler object in a global module like __init__.py and in the task files you can import this object.

I think I didn't get your question, a task is just a normal function, how would it be able to access the sheduler object "by default" ? 
Maybe you meant something like the ```current_app``` from Flask?

**Comment by nextcoder** [comment]
Yes, a task is a normal function, but it is invoked within your library. We could specify that if the programmer want the scheduler object in the task function, just define a named parameter that will be assigned the scheduler object at runtime.

This will allow all task to access application context stuff without having to do a global import. Does this make sense?

**Comment by viniciuschiele** [comment]
That's not simple to build because it is not my library that calls the tasks, my library just add endpoints to the Flask app to manage the tasks from [APScheduler](https://github.com/agronholm/apscheduler) which is another library.

**Comment by nextcoder** [comment]
I see. I remember looking into the function that invokes the function but now I remember that is jobs.py in the APScheduler not Flask-APScheduler. You are correct, it won't be easy at this level.

**Comment by trinanda** [comment]
> What do you mean by within a blueprint?
> A task is not related to a blueprint, you need to have access to the original Flask app instance to create a new app context.
> 
> You can access it using `apscheduler.app`.
> 
> e.g:
> 
> ```python
> scheduler = APScheduler()
> 
> def your_task():
>     app = apscheduler.app
>     with app.app_context():
>         users = User.query.all()
> ```

This solved my issue, thanks Man :)

**Comment by trinanda** [comment]
> ```
> scheduler = APScheduler()
> 
> def your_task():
>     app = apscheduler.app
>     with app.app_context():
>         users = User.query.all()
> ```
> 
> This only works if the scheduler is defined within the same module as the task. For any sizeable real-life application, the job most likely life in another file, so we have to make a global variable that can be imported from the separate module that contains the job.
> 
> Related to that, why isn't the scheduler object available from within the task by default?

This solved my issue, thanks Man :)

**Comment by andrequeiroz2** [comment]
> ```
> scheduler = APScheduler()
> 
> def your_task():
>     app = apscheduler.app
>     with app.app_context():
>         users = User.query.all()
> ```
> 
> Isso só funciona se o planejador for definido no mesmo módulo da tarefa. Para qualquer aplicativo considerável da vida real, o trabalho provavelmente está em outro arquivo, então temos que fazer uma variável global que pode ser importada do módulo separado que contém o trabalho.
> 
> Relacionado a isso, por que o objeto planejador não está disponível na tarefa por padrão?

obrigado apos dias tentando tudo, isso resolveu meu problema.
