### ISSUE TITLE
add_job() Function

### ISSUE THREAD

**Issue by jburchard** [viniciuschiele/flask-apscheduler#35]
Apologies if this is an obvious question, but in looking through the documentation, all of the examples load the jobs through the config. Does flask-apscheduler support add/remove job functions similar to ap-scheduler?

Here is my configuration:

```
SCHEDULER_JOBSTORES = {'default': SQLAlchemyJobStore(url='sqlite:///job_scheduler.db')}
SCHEDULER_EXECUTORS = {'default': {'type': 'threadpool', 'max_workers': 20}}
SCHEDULER_JOB_DEFAULTS = {'coalesce': False,'max_instances': 3}
```

When I've tried to run the add_job() function:

`scheduler.add_job(self.job_run,'interval',id=job_id,args=[self,job_id],seconds=15)`

it is throwing the following error

`TypeError: add_job() got multiple values for keyword argument 'id'`.

Thank you in advance and happy to provide more context if that would be helpful.

**Comment by viniciuschiele** [comment]
Hi,

That's possible, the signature of the add_job is a little bit different in my library, the job id is required.

Try this out:
```python
scheduler.add_job(job_id, self.job_run, trigger='interval', args=[self,job_id], seconds=15)
```

**Comment by jburchard** [comment]
That worked. Thank you so much for a) creating this library b) helping me troubleshoot.
