### ISSUE TITLE
Can the scheduler be run without running the flask app ?

### ISSUE THREAD

**Issue by rahulravindran0108** [viniciuschiele/flask-apscheduler#36]
Is it possible to start the apscheduler as a daemon running outside the flask app ? This is more of a question than an issue.

**Comment by viniciuschiele** [comment]
Hi, 

My library integrates APScheduler and Flask.

So if you don't need Flask I recommend you to use directly [APScheduler](https://apscheduler.readthedocs.io/en/latest/) which is not developed by me.

**Comment by rahulravindran0108** [comment]
My only concern is  can we have it running like celery. Here if the app fails I also lose my apscheduler process. At the same time I also want to leverage the API and the sqlalchemy job store present. So it is more about daemonizing it and make it fault tolerant.

**Comment by viniciuschiele** [comment]
You can have only one instance running at the same time otherwise you will see duplicated tasks running. If your requirement includes fault tolerant I'd recommend you to use Celery/Beat.

**Comment by viniciuschiele** [comment]
I will close this issue, feel free to open it again.
