### ISSUE TITLE
flask-apscheduler doen't work with uwsgi

### ISSUE THREAD

**Issue by yunho2141** [viniciuschiele/flask-apscheduler#37]
Hello,
I'm using flask-apscheduler with uwsgi on AWS EC2.

when I run on my mac it works well, but when I load it to on my server.

it does not work means no response or no action.

here is my config of flask and uwsgi.

please check.

I'm using python 2.7

[uwsgi]
base = /home/xx/app/api_server
module = application:application
virtualenv = %(base)/venv
master = true
processes = 5

socket = %(base)/udc.sock
chmod-socket = 660
uid=xx
gid=xx
vacuum = true
logto = %(base)/log/uwsgi.log
die-on-term = true
touch-reload = %(base)/reload

-----------------------------------------
in config.py

JOBS = [
            {
                'id': 'job1',
                'func': 'api.v1.mod_batch.batch:suggest_push',
                'trigger': {
                    'type': 'cron',
                    'day_of_week': 'mon,wed',
                    'hour': 8,
                    'minute': 15
                }
            },
            {
                'id': 'job2',
                'func': 'api.v1.mod_batch.batch:update_match_condtion_date',
                'trigger': {
                    'type': 'cron',
                    'hour': 14,
                    'minute': 47
                }
            },
        ]

**Comment by yunho2141** [comment]
by my self answer
it was solved by add enable-threads = true on uwsgi.ini file 

sorry

**Comment by eayin2** [comment]
Thanks, that helped me too!
