### ISSUE TITLE
Pausing scheduler doesnt work

### ISSUE THREAD

**Issue by mrabhiram** [viniciuschiele/flask-apscheduler#39]
Hi
I am trying to pause a schedule of concurrent jobs. I used 
     `scheduler.pause()`
when there comes a priority task. And also want to resume by `scheduler.resume()`, after the task is completed. It does not pause. It throws an internal error. Is there a way around to pause all the current scheduled jobs and resume them?
My config object looks like this.

```
class Config(object):
        JOBS = []
        for x in cache.get('Schedules'):
            temp_job = {}
            temp_job['id'] = x['ID']          # ID is unique
            temp_job['func'] = fun_Scheduler
            temp_job['args'] = [x['PIN'], x['Version']]           
            temp_job['trigger'] = "interval"
            temp_job['seconds'] = 10                                # Can change the interval to any number of seconds
            JOBS.append(temp_job)


        SCHEDULER_JOB_DEFAULTS = {
        'coalesce': False,
        'max_instances': 10
        }
        
        SCHEDULER_EXECUTORS = {
        'default': {'type': 'threadpool', 'max_workers': 30}
        }
       
        SCHEDULER_API_ENABLED = True
```

And the flask function to pause the scheduler is 

```
    @app.route("/patchAPI/<PIN>", methods=['GET'])
    def patchThem():
        scheduler.pause()
        resp=classic.patchPINCollection()  # This takes a while, so I am considering resuming it after this statement
        return(resp)
```
The scheduler works fine. Schedules all the jobs in the background.

But I do not get the response when I do `GET http:127.0.0.1:5001/patchAPI/09876`
I get an error like 
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

I have tried various other ways. But, couldn't find solution. Kindly, throw some insight on this.

Thank you

**Comment by viniciuschiele** [comment]
Hi

My APScheduler object does not expose the methods pause and resume, I will add them later on.

As a workaround you can get the original APScheduler object doing that:

```python
@app.route("/patchAPI/<PIN>", methods=['GET'])
    def patchThem():
        scheduler.scheduler.pause() # .scheduler gets the original APScheduler object
        resp=classic.patchPINCollection()
        return(resp)
```

**Comment by viniciuschiele** [comment]
Hi,
I've just released a new version that includes the methods pause and resume.

Now your previous code should work just fine.

**Comment by mrabhiram** [comment]
Hi,
Thank you. It worked perfectly fine. Just wanted to clarify something to get it right. 
      -> When we pause the scheduler, all the current working jobs complete their scheduled jobs and then pause. Is that correct? 
      -> Is there a way to execute jobs synchronously? One after the other? One job completes, notifies the next job in loop? Is there a way around that? I tried but couldn't figure out a way to do that.

Best

**Comment by viniciuschiele** [comment]
> When we pause the scheduler, all the current working jobs complete their scheduled jobs and then pause. Is that correct?

Yes, that is correct.

> Is there a way to execute jobs synchronously? One after the other? One job completes, notifies the next job in loop? Is there a way around that? I tried but couldn't figure out a way to do that.

If you need it synchronously why don't you just call the other job as a normal Python function?
Anyway, it is not possible to trigger another job within a job, such thing is only possible using [Celery](http://www.celeryproject.org/) which fits better complex job requirements.

**Comment by mrabhiram** [comment]
Thank you, for your info.
I am also trying to pause a particular job using job id. In the documentation it is said that we can do it by using job id. I am not able to get it.

`apscheduler.job_id.Job.pause()`

Is this the way?

The code I used to config jobs is above, the same. Could you tell me how to pause only one particular job?

**Comment by viniciuschiele** [comment]
I have to use pause_job:
```py
apscheduler.pause_job('job id')
```

**Comment by mrabhiram** [comment]
Thank you. I was also able to do the above by getting jobs using `get_jobs` and then selecting the particular job id.
