### ISSUE TITLE
Background/Blocking tasks

### ISSUE THREAD

**Issue by shr-chauhan** [viniciuschiele/flask-apscheduler#40]
Hi,
Just came across flask-apscheduler, actually i am writing an application with flask where I am using apscheduler, but i can see that flask-apscheduler is also available so I had a doubt
Like apscheduler we can pick wether we want to run a task as background or foreground(blocking), can we have that configuration here
scheduler = APScheduler()         //this does not provide any of that kind of config

I have a requirement where I want to run a task(cron/interval) on the basis of a post request, can that be achieved using this?

Thanks for any kind of help

**Comment by viniciuschiele** [comment]
Hi,

You can pass in your own APScheduler object to Flask-APScheduler.
  
```python
from apscheduler.schedulers.background import BackgroundScheduler
from flask_apscheduler import APScheduler

scheduler = APScheduler(BackgroundScheduler())
````
Does it help you? If not, show me the code you are doing with APScheduler so I can show you how to do the same with Flask-APScheduler.

Cheers

**Comment by shr-chauhan** [comment]
Thanks, got it 
this is fine, but somehow I am not able to get it working on a rest post request
example structure,
api
    v2_0
        scheduler.py       
app.py


in scheduler.py, I have a post method on a URL where I am doing this
scheduler.add_job(id='12344perform',func='background_tasks.schedule:immediate_task',trigger='interval',seconds=5)



in app.py 
from flask_apscheduler import APScheduler
scheduler = APScheduler()
def create_app(config_name):
       scheduler.init_app(app)
       scheduler.start()


Just given the apscheduler related configuration, running it on a local flask server as of now, so when i run it create_app method gets triggered.
Dont know what am I doing wrong, but the task(background_tasks.schedule:immediate_task) is not getting triggered when I hit the URL...
Thanks for any help with this

**Comment by shr-chauhan** [comment]
this is the structure

api-
----v2_0-
--------scheduler.py
background_tasks-
----schedule.py
app.py

**Comment by viniciuschiele** [comment]
Hi,

If I understood well, you have an flask endpoint that adds a new task in APScheduler, this task is executed on background every 5 seconds.

This code below is an example of this and it works well for me:

```python
from datetime import datetime
from flask import Flask, Response
from flask_apscheduler import APScheduler


def job1():
    print(datetime.now())


app = Flask(__name__)
scheduler = APScheduler()


@app.route('/add_task', methods=['POST'])
def add_task():
    task_id = str(datetime.now())

    scheduler.add_job(task_id, 'rest:job1', trigger='interval', seconds=5)
    return Response()


if __name__ == '__main__':
    scheduler.init_app(app)
    scheduler.start()

    app.run()
```
```bash
curl -X POST http://127.0.0.1:5000/add_task
```

Maybe you could enable the logs for APScheduler to see what's going on.

**Comment by shr-chauhan** [comment]
yea task is running, but somehow not able to produce the logs for the scheduler
i tried with an example, and i used this basicConfig like this
import logging
logging.basicConfig(filename='/var/log/testsched', level=logging.DEBUG,format='[%(asctime)s]: %(levelname)s : %(message)s')

which worked fine for me, but somehow in my project log file itself is not getting generated

**Comment by shr-chauhan** [comment]
so logging configuration is kinda tricky, so I already have a logging setup which I dont want to tweak, so because of that logging.basicConfig() is not working, can you help me in figuring out how can I make it work, without really disturbing the current logging functionality.
This is my logging_config.py file:

'''
set and configure a common module logger
'''
import logging
import logging.handlers
import os
from common import configuration

log_folder = configuration.system['log_folder']
if not os.path.exists(log_folder): os.mkdir(log_folder)
applogger = logging.getLogger(configuration.system['app_name'])
# applogger.addHandler(logging.StreamHandler())
#do not propogate logs to the root logger
applogger.propagate = False
logging_level = logging.DEBUG

# logging.basicConfig(filename='/var/log/apschedule', level=logging.DEBUG,format='[%(asctime)s]: %(levelname)s : %(message)s')

def configure_app_logger(debug=False):
    '''configure common moudle logger'''
    global applogger
    global logging_level
    if debug:
        log_level = logging.DEBUG
        log_formatter = logging.Formatter(\
        fmt='%(asctime)s : %(levelname)-8s %(message)-81s <- %(module)s.%(funcName)s, line %(lineno)d',\
        datefmt='%d/%b/%y %I:%M:%S%p')
    else:
        log_level = logging.INFO
        log_formatter = logging.Formatter(fmt='%(asctime)s : %(levelname)-8s %(message)s',\
                                          datefmt='%d/%b/%y %I:%M:%S%p')
    logging_level = log_level
    file_handler = logging.handlers.WatchedFileHandler(
    os.path.join(log_folder, '{a}.log'.format(a=configuration.system['app_name'])))
    file_handler.setLevel(log_level)
    file_handler.setFormatter(log_formatter)
    console_handler = logging.StreamHandler()
    console_handler.setLevel(log_level)
    console_handler.setFormatter(log_formatter)
    applogger.setLevel(log_level)
    applogger.addHandler(file_handler)
    applogger.addHandler(console_handler)

**Comment by viniciuschiele** [comment]
If I'm not wrong, APScheduler logs its logs in the logger name **apscheduler.executors.default**

I think you need to set up a logger with this name.

```python
logger = logging.getLogger('apscheduler.executors.default')
logger.addHandler(...)
logger.addHandler(...)
```

I'm not sure this code above will work, that is just a guess.

**Comment by shr-chauhan** [comment]
Bang on...thanks mate
did not know about apscheduler.executors.default, as basicConfig worked for me so never looked into this....so now I created a new logger for scheduler with a different set of config and all works well for me now

Cheers

**Comment by viniciuschiele** [comment]
I'm glad to hear that.

Cheers
