### ISSUE TITLE
flask main thread is hang ,not handler request

### ISSUE THREAD

**Issue by chestarss** [viniciuschiele/flask-apscheduler#41]
#scheduler.py
`JOBS = [
        {
        'id': 'just test',
        'func': '__builtin__:print',
        'args': ('test .......',),
        'trigger': 'interval',
        'seconds': 5,
    }
]
`
#runserver.py 
from flask import Flask
from flask_apscheduler import APScheduler
app = Flask('myapp')
app.config.from_pyfile('./scheduler.py')
apscheduler = APScheduler(app=app)
apscheduler.start()
app.run()

##thread info 
###:~$ sudo ps H -C python -o 'pid tid cmd'
  PID   TID CMD
19690 19690 python runserver.py
19690 19699 python runserver.py
19690 19700 python runserver.py
19690 19701 python runserver.py

the apscheduler can execute, but flask can not handler http request

port 5000 open and listening,  when i curl localhost:5000  , it will block forever.

**Comment by viniciuschiele** [comment]
what does your Flask endpoint do?
 
APScheduler runs on its own thread,  I don't see how it could happens.

**Comment by chestarss** [comment]
:~$ ps H -C python -o 'pid tid cmd'
  PID   TID CMD
26657 26657 python runserver.py
26657 26664 python runserver.py
26657 26665 python runserver.py
26657 26666 python runserver.py
:~$ sudo strace -p 26664
Process 26664 attached - interrupt to quit
futex(0x7f64a9ae02bc, FUTEX_WAIT_PRIVATE, 1, NULL

**Comment by viniciuschiele** [comment]
Are you sure the issue is not in the Flask endpoint? Can you post entire code?

**Comment by viniciuschiele** [comment]
Feel free to open this issue again.
