### ISSUE TITLE
how does SQLAlchemyJobStore create a rable in DB

### ISSUE THREAD

**Issue by shr-chauhan** [viniciuschiele/flask-apscheduler#42]
Hi , have been using flask-APscheduler and it has been working really well for me,
but now I am not able to figure out this jobstore issue
I am trying to create a native job store, never had the requirement before , so I tried something like this

'''
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
jobstores = {
    'default': SQLAlchemyJobStore(url='postgresql+psycopg2://uname:pass@localhost/test_db',tablename='apscheduler_jobs')
}
scheduler    = APScheduler(BackgroundScheduler(jobstores=jobstores))

'''

This I used once with APScheduler, but with flask i dont think jobstore is working at all(even if i give non existing db name, it does not give any error, table also not getting created for right db name), I dont want to do it through a config class, cause all my tasks are dynamic and i dont use config class for those, so just for jobstore i dont want to create  a separate task, plus i have all my configurations for the app already set
Is this the right workaround? any issue with this? if not then how it should be done 

any suggestions?

**Comment by viniciuschiele** [comment]
The table is created when you start the scheduler, make sure your user has permission to create tables in your database.

**Comment by viniciuschiele** [comment]
I'm closing this issue, feel free to open it again.
