### ISSUE TITLE
how to unschedule a job in flask-apscheduler using id?

### ISSUE THREAD

**Issue by shr-chauhan** [viniciuschiele/flask-apscheduler#43]
I want to unschedule a running job from inside the job, but i am not able to figure the work around for this
something like this I have used before, in apscheduler: **scheduler.unschedule_job(schedule_task.job)**

i tried using : scheduler.delete_job('job1')

I wrote a basic code(just an example), where i am trying to stop the job once it reaches id limit 
code:flaskAPSched.py
'''
from flask import Flask
from flask_apscheduler import APScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.schedulers.background import BackgroundScheduler
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:postgres@localhost:5432/scheduler'
db = SQLAlchemy(app)

class Test(db.Model):
    __tablename__        = 'testing'
    id=db.Column(db.Integer, primary_key=True,autoincrement=True)
    name=db.Column(db.String(200))
    def __init__(self, name):
        self.name=name

class Config(object):
    JOBS = [
        {
            'id': 'job11',
            'func': 'flaskAPSched:job1',
            'args': ('Shrey'),
            'trigger': 'interval',
            'seconds': 5
        }
    ]

db.create_all()
db.session.commit()

def job1(a):
    s=Test(name=a)
    db.session.add(s)
    db.session.commit()
    x=db.session.query(func.max(Student.id).label("max_id")).one().max_id
    print x
    if x==5:
        print "limit reached"
        scheduler.delete_job('job1')
    print(str(a) + ' ' + str(b))

if __name__ == '__main__':
    app = Flask(__name__)
    app.config.from_object(Config())
    scheduler = APScheduler()
    scheduler.init_app(app)
    scheduler.start()
    app.run()

'''

what i am trying to achieve is, after putiing 5 entries, scheduler should stop executing the job
but nothing is happening, job just keep executing and does not stop at all

is this the right way of doing it, or there is any other way to unschedule a job?

**Comment by viniciuschiele** [comment]
Are you using one single .py file to initialise the scheduler and to define your task? If so, it is not going to work because APScheduler will reload the same .py file and it will re-instantiate all your objects.

Split your project in two files, like app.py and tasks.py

app.py initialises Flask and APScheduler and in tasks.py you put your task methods.

I hope this works for you.

**Comment by viniciuschiele** [comment]
And also the way you built this code, the variable ```scheduler``` is not accessible within your task.

**Comment by shr-chauhan** [comment]
so are you saying that **scheduler.delete_job('job1')** is the right way of unscheduling a job?
and if jobstore in my config, like this
class Config(object):
    JOBS = [
        {
            'id': 'job1',
            'func': 'sjobs:job1',
            'args': ("Shrey"),
            'trigger': 'interval',
            'seconds': 5
        }
    ]
    SCHEDULER_JOBSTORES = {
    'default': SQLAlchemyJobStore(url='postgresql://postgres:postgres@localhost:5432/scheduler',tablename='apscheduler')
    }

I have this config, with a jobstore(taken from example, just changed sqlite to postgres), do I have to give the jobstore name in the delete call, if yes then what it is? basically i want to delete the job from the jobstore



and one more doubt is, is there a way to delete a job from inside the job, without using the id....something like self.id gives id of the running job, or any workaround for that?

**Comment by viniciuschiele** [comment]
You don't need to give the jobstore name, just call delete_job passing the job name.

Unfortunately there is no way to get the current job within a job using ```self````, if you really need that, you can open an issue for [APScheduler](https://github.com/agronholm/apscheduler)

**Comment by shr-chauhan** [comment]
so does delete_job(id) deletes the job from jobstore, or it just stop executing it?

**Comment by viniciuschiele** [comment]
it will delete the job and stop executing it.

**Comment by shr-chauhan** [comment]
Thanks man...its working well 

One more doubt that I have though, what about HA(High availability) is there anything can be done from APscheduler's point of view, like db sync or something which makes sure that it never goes down

**Comment by viniciuschiele** [comment]
No, APScheduler doesn't give any HA feature, you need to do it by yourself.

In my company we use **uwsgi legion** to keep one server as active and the others as stand by, so if the active server fails, uwsgi legion will start the APScheduler App in one of the other servers.

**Comment by shr-chauhan** [comment]
alright...so to my understing legion is not just for APscheduler right?
basically if the server on which app is running fails, it will bring up
 the app on the other node(the whole app, or you have a dedicated node just
for apscheduler?), wont it effect your scheduled jobs? or it will pick up
from the jobstore without causing any issue?

**Comment by viniciuschiele** [comment]
You are right, legion is for any application.

If the server fails it will bring up all apps that are part of this legion on the other server.
I'm not aware of the details because we have a system engineer that manages that for us.

As long as your jobs are stored in database, you shouldn't have any issue.

**Comment by shr-chauhan** [comment]
alright...thanks man
But before we close this discussion one naive doubt?
Say I dont have a legion setup done and I have a restful app which has apshceduler running in it, and I have 2 instances of the app running on 2 servers with the shared database, basically jobstore is same....so if a job gets scheduled, it will be served by both the apps right? or which ever server picks it up ony that will execute it...

**Comment by viniciuschiele** [comment]
Hi,

Yeah, it will probably run by both apps.

**Comment by shr-chauhan** [comment]
thanks man, we can close this
