### ISSUE TITLE
Use cron-like Scheduling in flask-apscheduler

### ISSUE THREAD

**Issue by 1qase4** [viniciuschiele/flask-apscheduler#44]
I want my job work in regular time, in apscheduler I can set like this
`sched.add_job(my_job, 'cron', year=2017,month = 03,day = 22,hour = 17,minute = 19,second = 07)`
but  I do not know how to set it in flask-apscheduler?

thinks for answer!

**Comment by viniciuschiele** [comment]
If you are using a config object to load your tasks you can do that:

```python
class Config(object):
    JOBS = [
        {
            'id': 'job1',
            'func': '__main__:job1',
            'trigger': 'cron',
            'year': 2017,
            'month': 3,
            'day': 22,
            'minute': 19,
            'second': 7
        }
    ]
```

**Comment by shr-chauhan** [comment]
this might help 

scheduler.add_job(id=job_id1 ,func='__main__:my_job',trigger='cron',year=2017,month = 03,day = 22,hour = 17,minute = 19,second = 07)

where __main__ is your module where you have written your function(my_job), give your module name there

**Comment by 1qase4** [comment]
i see , thinks!
