### ISSUE TITLE
Where to find Config parameter documentation?

### ISSUE THREAD

**Issue by Dewsworld** [viniciuschiele/flask-apscheduler#46]
Hello,
First of all, thank you for such a useful library. I have googled for aps-scheduler config parameter. For example,
`    JOBS = [
        {
            'id': 'job1',
            'func': 'jobs:job1',
            'args': (1, 2),
            'trigger': 'interval',
            'seconds': 10
        }
    ]
`
I would like to get a documentation for all available parameters and their possible values.

**Comment by viniciuschiele** [comment]
Hi @Dewsworld 

Unfortunately there is no official Flask-APScheduler documentation, [APScheduler](https://apscheduler.readthedocs.io/en/latest/) also lacks documentation.

What I can tell you is that you can use any parameter from add_job in your job config.

On APScheduler's website you can see what are the triggers available and its parameters.
 
http://apscheduler.readthedocs.io/en/latest/modules/triggers/date.html
http://apscheduler.readthedocs.io/en/latest/modules/triggers/interval.html
http://apscheduler.readthedocs.io/en/latest/modules/triggers/cron.html

I will soon add more examples for each type of trigger.

**Comment by viniciuschiele** [comment]
I'm closing this issue as another issue has been opened for documentation #49.
