### ISSUE TITLE
App Crashing During Fetch: AttributeError: 'NoneType' object has no attribute 'now'

### ISSUE THREAD

**Issue by jonsimington** [viniciuschiele/flask-apscheduler#5]
Ran into this error after hosting my flask application on my VirtualBox instance of Ubuntu 14.04.

I never ran into this issue when hosting the application with Windows 7.

![error](https://cloud.githubusercontent.com/assets/5304384/9207341/97f74658-4032-11e5-9adb-fe3a45acef70.png)

Any Ideas?

**Comment by viniciuschiele** [comment]
This line caused the error:
```python
now = datetime.now(self.timezone)
```
It seems the Python is not well installed.

Could you run those lines below on the same project? Just to make sure datetime object is working properly.

```python
from datetime import datetime
now = datetime.now()
```

**Comment by viniciuschiele** [comment]
@jonsimington 

Do you still have this issue?

**Comment by jonsimington** [comment]
Sorry.  I meant to update you about a month ago ^.^

The dev who was having this problem had a wonky virtualenv set up which caused parts of python (datetime, etc) to not be recognized.  We fixed it and it had nothing to do with flask-apscheduler :D
