### ISSUE TITLE
Cannot understand how to use it with flask_script manager and also with apache2

### ISSUE THREAD

**Issue by deveshaggrawal19** [viniciuschiele/flask-apscheduler#50]
Can you please help me in setting up the apscheduler with flask manager and apache2.
If I run scheduler.start() then it shows that the scheduler is already running if i user shutdown then it is showing it is not running. Please help me. Thanks in advance

**Comment by viniciuschiele** [comment]
Can you provide an example of what you are trying to accomplish?

**Comment by deveshaggrawal19** [comment]
I am trying to make a set of functions so that it can change the values in redis_db

**Comment by viniciuschiele** [comment]
I can't help you without an example, can you post here how you are initializing Flask and APSchduler?

**Comment by deveshaggrawal19** [comment]
I am using flask manager for developement server and apache2 for production server.


Below is the code for manag.py:
import os
from app import create_app, db
from app.models import User, Order, Contact, Wallet, Withdraw, Deposit, Transaction, Subscription
from flask_script import Manager, Shell
from flask_migrate import Migrate, MigrateCommand
def make_shell_context():
    return dict(app=app, db=db, User=User)
app = create_app('development')
manager = Manager(app)
migrate = Migrate(app, db)
manager.add_command("shell", Shell(make_context=make_shell_context))
manager.add_command('db', MigrateCommand)
if __name__ == '__main__':
    scheduler.start()
    manager.run()


Below is the code for __intit__.py:
from flask import Flask
from flask_sqlalchemy import SQLAlchemy     # using orm wrapper around sqlalchemy
from flask_login import LoginManager        # for login sessions
from . import config              # config file having different configurations
import redis
from flask_apscheduler import APScheduler
db = SQLAlchemy()
redis_db = redis.StrictRedis(host='localhost', port=6379, db=0)
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'     # Default login page, after any bad requests
 scheduler = APScheduler()
import app.models
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config.config[config_name])
    config.config[config_name].init_app(app)
    login_manager.init_app(app)
    db.init_app(app)
    scheduler.init_app(app)
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    # attach routes and custom error pages herereturn app
    return app
app = create_app('development')

**Comment by viniciuschiele** [comment]
Where do you start APScheduler?

The only place I see it in your code is here:

```python
if name == 'main':
    scheduler.start()
    manager.run()
````

But I think this code above isn't being executed with Apache2.

I would suggest you to start APScheduler within ```create_app```:

```
def create_app(config_name):
    ....    
    scheduler.start()
```

I hope it helps you out

**Comment by deveshaggrawal19** [comment]
I have not tested it on apache2, I was thinking first to test it on local flask server, that is why I had placed scheduler.start in the manager. If I put it inside the create_app then it returns that the schedular is already running. But with schedular.start() inside the manager, it gives the error that the job is already running

**Comment by viniciuschiele** [comment]
Just for testing, I've built this example similar to yours, it works well.

```python
from flask import Flask
from flask_apscheduler import APScheduler
from flask_script import Manager, Shell

scheduler = APScheduler()


def create_app():
    app = Flask(__name__)
    scheduler.init_app(app)
    scheduler.start()
    return app


def make_shell_context():
    return dict(app=app)


app = create_app()

manager = Manager(app)
manager.add_command("shell", Shell(make_context=make_shell_context))

if __name__ == '__main__':
    manager.run()
```

```
python main.py runserver
```

Try to run it and see what happens.

**Comment by deveshaggrawal19** [comment]
Can it be that I am using different files for manager and __init__, it is happening

**Comment by viniciuschiele** [comment]
That makes no difference.

Before you got **scheduler is already running** because you are calling twice ```create_app('development')```

**Comment by deveshaggrawal19** [comment]
creat_app('development') is for apache. Can you suggest any configuration that can work with both apache and flask?

**Comment by viniciuschiele** [comment]
Usually I create two files, one to run locally and another one for uwsgi/gunicorn/apache.

e.g:

```py
# myapp.py
# my app logic goes here

def create_app():
    return Flask(__name)
```

```py
# run.py
# used to run locally

from myapp import create_app

if __name__ == '__main__':
    manager = Manager(create_app())
    manager.run()
```

```py
# wsgi.py
# used to run on uwsgi/apache

from myapp import create_app

application = create_app()
```

**Comment by deveshaggrawal19** [comment]
thanks for all the help
