### ISSUE TITLE
Multiple instances of shceduler problem

### ISSUE THREAD

**Issue by shr-chauhan** [viniciuschiele/flask-apscheduler#51]
I had a doubt, about using flask-apscheduler in  a web app
When used in any forking web server (gunicorn uwsgi, etc...), processes get forked, thus apacheduler gets instantiated (and possibly started) in each forked worker process. This leads to the "many jobs running" issue? 
In production multiple instances of the app gets created, it will initiate that many scheduler instances also right? so all those instances will try executing the job is it?
Am I wrong here?

**Comment by viniciuschiele** [comment]
yeah, your assumption is right, it will start one scheduler for each forked process and it will run the same job multiple times.
If you are running this service on multiple servers, you could keep only one active and the others as idle, 
we achieved it using uwsgi legion.

**Comment by everhopingandwaiting** [comment]
```
            if os.environ.get("scheduler_lock") == "1":
                scheduler.start()
                logging.debug("Schedular Started ,-------------")
                os.environ["scheduler_lock"] = os.environ.get("scheduler_lock") + "1"

```

before start the program ,you had better to ` export  scheduler_lock="1"`

**Comment by shr-chauhan** [comment]
Sorry for the late update
@everhopingandwaiting  yea that is one way of doing it, but I am doing it differently
Running scheduler as a rpc server outside the app, so its a different process now....so whenever there is a scheduling request, it gets connected to the rpc and process the request there....

@viniciuschiele closing this

**Comment by everhopingandwaiting** [comment]
![screenshot_2017-09-02-13-06-26-788_com sonelli juicessh](https://user-images.githubusercontent.com/6021724/29993096-adef1d38-8fdf-11e7-9daf-a38a35cbb7b7.png)


@viniciuschiele @viniciuschiele  fcntl mscvrt

**Comment by chenxuewen** [comment]
Why did you add this code? Unable to dynamically modify timing tasks?


import atexit
import fcntl
from apscheduler.events import EVENT_JOB_ERROR, EVENT_JOB_MISSED, EVENT_JOB_EXECUTED
def scheduler_init(app):

    f = open("scheduler.lock", "wb")
    try:
        fcntl.flock(f, fcntl.LOCK_EX | fcntl.LOCK_NB)


        scheduler.add_listener(job_listener, EVENT_JOB_ERROR | \
                           EVENT_JOB_MISSED | \
                           EVENT_JOB_EXECUTED)
        scheduler.init_app(app)
        scheduler.start()
    except:
        pass
    def unlock():
        fcntl.flock(f, fcntl.LOCK_UN)
        f.close()
    atexit.register(unlock)
