### ISSUE TITLE
How do you get an app with flask-apscheduler to run on Heroku?

### ISSUE THREAD

**Issue by spitfiredd** [viniciuschiele/flask-apscheduler#56]
@viniciuschiele 

This is a question and not an issue, I have built a flask app with APS-scheduler and I have a few jobs that run and gather data and store them in a database.  Now, I would like to run my app on Heroku and I was wondering how I would accomplish that task?

Thanks!

**Comment by viniciuschiele** [comment]
Hi @spitfiredd 

What issues are you running into?

I've never used Heroku so I don't know if it will allow your app to spawn new threads in the background to run your tasks.
Apart from that, it should work just fine, it is just a flask app like any other.

**Comment by amajeed-dinCloud** [comment]
@spitfiredd  I think you are looking for this:

[Scheduled Jobs with Custom Clock Processes in Python with APScheduler](https://devcenter.heroku.com/articles/clock-processes-python)
