### ISSUE TITLE
Start the scheduler in paused state

### ISSUE THREAD

**Issue by fitamant** [viniciuschiele/flask-apscheduler#59]
Hi,

I would like to start the scheduler in paused state as the library APScheduler allows. Can you add this ?

scheduler.start(paused=True)

Thanks a lot,
Best regards

**Comment by viniciuschiele** [comment]
Hi,

I've just pushed the code, I will release a new version soon.

Thanks

**Comment by viniciuschiele** [comment]
Done

**Comment by beshe** [comment]
Hi,
A great enhancement, and it's for global, right? Is it possible to implement by separate job also? say add the option for the initial value when add new scheduler job?
Thanks
