### ISSUE TITLE
Security Hole: flask_apscheduler.APScheduler.init_app() always adds Jobs UI

### ISSUE THREAD

**Issue by adroffner** [viniciuschiele/flask-apscheduler#6]
The Jobs UI allows anyone to see the jobs list & run a job ID. There is no authentication scheme to protect the job control. This is a major security hole.

The real problem is APScheduler.init_app() always adds Jobs UI endpoints. Please, add a flag to the constructor & init_app methods so that the Job UI can be left out of the Flask routes (I recommend this as the default).

NOTE:
For now,  I am overriding the method to ignore __load_views() so that it doesn't make  the routes.

**Comment by viniciuschiele** [comment]
@adroffner 

Definitely that is a good idea, I will add a new flag in the flask config object to enable the views, the default will be False.

e.g:
```python
app.config['APSCHEDULER_VIEWS'] = True
```
I will try to release a new version today.

Cheers!

**Comment by viniciuschiele** [comment]
I have added a new flag called SCHEDULER_VIEWS_ENABLED to enable/disable the views, by default it is False.

```python
app.config['SCHEDULER_VIEWS_ENABLED'] = True
```
