### ISSUE TITLE
How to disable `_load_jobs` on startup ?

### ISSUE THREAD

**Issue by eromoe** [viniciuschiele/flask-apscheduler#60]
Hello, 

I  have some predefined job code , need remote client's request  to start this job and set cron/ interval .

```
    JOBS = [
        {
            'name': 'job1',
            'func': 'scheduler.jobs.bid:test_writefile',
            'max_instances': 1,
            'coalesce': True,
        }
    ]
```

But got error : 

```
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    app = create_app(app_name='basin-scheduler')
  File "Z:\bidspy-yychen\scheduler\scheduler\app.py", line 23, in create_app
    configure_extentions(app)
  File "Z:\bidspy-yychen\scheduler\scheduler\app.py", line 43, in configure_extentions
    scheduler.init_app(app)
  File "D:\Python27\lib\site-packages\flask_apscheduler\scheduler.py", line 68, in init_app
    self._load_jobs()
  File "D:\Python27\lib\site-packages\flask_apscheduler\scheduler.py", line 286, in _load_jobs
    self.add_job(**job)
TypeError: add_job() takes exactly 3 arguments (2 given)
```

source code need an id, 
```
    def add_job(self, id, func, **kwargs):
```

But id would  only obtain in running time .

**Comment by viniciuschiele** [comment]
Hi,

The ID of the job is required otherwise every time you run your app it would add a new job in the job store.

Why don't you set the ID as 'job1' ? If you a remote client needs to change the job it needs to know the Job ID anyway.

**Comment by eromoe** [comment]
I mean the id come from remote client.  It may create thousand of jobs . All jobs are 'scheduler.jobs.bid:test_writefile'  , just id different and the trigger may be cron or interval , schedule may be every day, may be every week or something else .   So I can't predefine job in config.

**Comment by viniciuschiele** [comment]
Not sure if I understood it well.

It is not possible to have predefined jobs in the config file and start it with a different ID. 

If you want to add new jobs on the fly using a remote client you can call the endpoint ```POST /scheduler/jobs``` to add new jobs. For example, every time a customer submits an order you can call this endpoint to add a new job, but that means the remote client must send the job definition (func, max_instances, ... )
