### ISSUE TITLE
This 'trigger': 'cron' is not valid of Docker Debian 8 

### ISSUE THREAD

**Issue by enjoyZhou** [viniciuschiele/flask-apscheduler#63]
Is it related to the system crontab？
This configuration is not valid of Debian 8：
`{`
            `'id': 'auto_order_shot_notice',`
            `'func': 'func:auto_order_shot_notice',`
           ` 'trigger': 'cron',`
            `'args': [True],`
           ` 'day_of_week': 'mon-sun',`
            `'hour': 12`
        }`

**Comment by viniciuschiele** [comment]
Hi,

APScheduler has its own implemention of crontab but it should be fully compatible.

You can see it here: https://github.com/agronholm/apscheduler/tree/master/apscheduler/triggers/cron

I don't have Debian but I just tested your code above on Ubuntu and it worked as expected.
