### ISSUE TITLE
delete_job should be remove_job

### ISSUE THREAD

**Issue by afourmy** [viniciuschiele/flask-apscheduler#64]
In APScheduler, the method to remove / delete a scheduled job is `scheduler.remove_job()`. In flask_apscheduler, it was renamed `delete_job()`. Why is that ?
The method names should be the same.

**Comment by viniciuschiele** [comment]
Hi,

No real reason, but I agree with you, better keep them with the same name.

I could add a new method ```remove_job``` and mark ```delete_job``` as deprecated using ```warnings.warn```

If you wish you can create a pull request to fix it.

**Comment by afourmy** [comment]
OK, I will make a PR when I've got some time.

**Comment by viniciuschiele** [comment]
Hi,

I just pushed the code to add ```remove_job``` and ```remove_all_jobs```.

**Comment by viniciuschiele** [comment]
Hi,

I deployed the version 1.8.0 with those new methods.
