### ISSUE TITLE
Get the scheduler state

### ISSUE THREAD

**Issue by fitamant** [viniciuschiele/flask-apscheduler#65]
Hi,

I would like to get the scheduler state (running, paused, stopped) as the library APScheduler allows :

> apscheduler.schedulers.base.STATE_STOPPED = 0
> constant indicating a scheduler’s stopped state
> 
> apscheduler.schedulers.base.STATE_RUNNING = 1
> constant indicating a scheduler’s running state (started and processing jobs)
> 
> apscheduler.schedulers.base.STATE_PAUSED = 2
> constant indicating a scheduler’s paused state (started but not processing jobs)

Can you add this ?

Thanks a lot,
Best regards

Yannick

**Comment by viniciuschiele** [comment]
Hi,

Sure, I will add it this weekend.

In the meantime, you can also access it like that:

```python
from flask_apscheduler import APScheduler
scheduler = APScheduler()
state = scheduler.scheduler.state
```

**Comment by viniciuschiele** [comment]
Hi,

I deployed the version 1.8.0 with this new property where you can get the scheduler state.

e.g:
```python
from flask_apscheduler import APScheduler, STATE_STOPPED

scheduler = APScheduler()
print(scheduler.state == STATE_STOPPED)
```
