### ISSUE TITLE
Too many Threads

### ISSUE THREAD

**Issue by Doncode** [viniciuschiele/flask-apscheduler#67]
I can see to many Threads. Is it Ok?

![image](https://user-images.githubusercontent.com/1270917/37738230-5f6259e8-2d67-11e8-88de-a2d16e25422e.png)

**Comment by viniciuschiele** [comment]
Hi.

It might happen if you have concurrent jobs being executed, by default APScheduler spawns up to 10 threads.

If you google for APScheduler max_workers you will have more details.
