### ISSUE TITLE
Persistent JobStores cannot be uses because replace_existing=True isn't set

### ISSUE THREAD

**Issue by adroffner** [viniciuschiele/flask-apscheduler#7]
APScheduler.__load_job(job, app) does not allow "replace_existing=True" to be passed to add_job(). Persistent Jobstores, e.g. SQLAlchemyJobStore, will not rewrite a previously declared job_id without it.

I get an exception when my Flask server restarts. The same job ID can't be written to sqlite3 twice.

See here:
http://apscheduler.readthedocs.org/en/v3.0.3/userguide.html?highlight=replace_existing#adding-jobs

**Comment by viniciuschiele** [comment]
Could you explain me why are you using sqlite to store the jobs at the same time that you are loading them from a configuration file?

**Comment by viniciuschiele** [comment]
I have added more parameters for the job definition, among them replace_existing.

```python
JOBS = [
    {
        'id': 'job1',
        'func': '__main__:job1',
        'args': (1, 2),
        'trigger': {
            'type': 'cron',
            'second': 10
        },
        'replace_existing': True
    }
]
```

**Comment by adroffner** [comment]
I understand that a job should either come from a python configuration or a jobstore DB. But if there's a conflict, the programmer might want to overwrite the jobstoreDB sometimes.
