### ISSUE TITLE
Adding task errors via api interface

### ISSUE THREAD

**Issue by zhangyao8** [viniciuschiele/flask-apscheduler#73]
POST  http://127.0.0.1:5000/scheduler/jobs add task
POST body
`{"id":"job3","func": "jobs:job1","args":"11","trigger":"interval","seconds":10}`
return
```
{
    "id": "job3",
    "name": "job3",
    "func": "jobs:job1",
    "args": [
        "1",
        "1"
    ],
    "kwargs": {},
    "trigger": "interval",
    "start_date": "2018-05-02T16:54:43.103900+08:00",
    "seconds": 10,
    "misfire_grace_time": 1,
    "max_instances": 1,
    "next_run_time": "2018-05-02T16:54:43.103900+08:00"
}
```

args --> Iterate 11 to 1，1

-----------------------------------------------------------------------------
post 
`{"id":"job3","func": "jobs:job1","args":"(11,22)","trigger":"interval","seconds":10}`

result 
```
{
    "error_message": "The list of positional arguments is longer than the target callable can handle (allowed: 2, given in args: 7)"
}
```

---------------------------------------------------------------------------
flask_apscheduler\api.py  
 Line 38
` data = request.get_json(force=True)`

ex:
Add a row
`print(data,type((data['args'])))`
output
`{'id': 'job3', 'func': 'jobs:job1', 'args': '(11,22)', 'trigger': 'interval', 'seconds': 10} <class 'str'>`

apscheduler\schedulers\base.py

Line412
```
        job_kwargs = {
            'trigger': self._create_trigger(trigger, trigger_args),
            'executor': executor,
            'func': func,
            'args': tuple(args) if args is not None else (),
            'kwargs': dict(kwargs) if kwargs is not None else {},
            'id': id,
            'name': name,
            'misfire_grace_time': misfire_grace_time,
            'coalesce': coalesce,
            'max_instances': max_instances,
            'next_run_time': next_run_time
        }
```

**args need tuple not str**

Solution
```
    data = request.get_json(force=True)
    data['args'] = eval(data['args'])
```

**Comment by viniciuschiele** [comment]
Hi,

Why you don't send the "args" field as a list?

e.g:
```json
{
   "id":"job3",
   "func":"jobs:job1",
   "args":[
      11,
      22
   ],
   "trigger":"interval",
   "seconds":10
}
```

**Comment by zhangyao8** [comment]
The POST of the json string is sent to the API interface, and the server always recognizes the args parameter as a string type. Finally, converting this string type into a tuple will be an error.

e.g:
```
t=str((1,2))
print(tuple(t))
```

result
`('(', '1', ',', ' ', '2', ')')`

original:
apscheduler\schedulers\base.py

Line416

`            'args': tuple(args) if args is not None else (),`


(APScheduler-3.5.1)

**Comment by viniciuschiele** [comment]
The server is expecting a list/array for args field and it won't change, you are sending a string instead of a list.

I will add a validation on the server side to return an error if args is not a list.

**Comment by zhangyao8** [comment]
I just understood what you mean, the 'arg' format needs to be a list，thanks
