### ISSUE TITLE
Issues with application context in production

### ISSUE THREAD

**Issue by dhhagan** [viniciuschiele/flask-apscheduler#78]
Perusing through the open and closed issues here, it seems like application context is often an issue. Through several other issues, I have successfully been able to use flask-apscheduler on a local development site perfectly; however, when switching to production, I see errors associated with the application context.

I have a fully-built, large flask app in the format laid out via Miguel Grinberg's tutorial series/books. Generally speaking, the file structure is as follows:

<pre>
/app
/app/__init__.py
/app/admin/views.py
...
config.py
manage.py
</pre>

There is plently more where that came from, but that should more or less convey the point. I am loading jobs via the config file as demonstrated in your examples. Right now, they are calling several functions located in the `/app/admin/views.py` file. They look something like:

<pre>
def gen_results():
    with scheduler.app.app_context():
        i = Model.query.filter(<filtering here>)
        for each in i.all():
            print (each.some_attr)
</pre>

In development, this works without issue as I use the flask-socketio development server. In production, I use gunicorn with gevent and it throws context errors as can be viewed [here][1].

I really don't know what to even look for or try at this point; clearly, I don't understand enough about the Flask application context to properly debug. Are there any examples of flask-apscheduler being used in a fully-fledge Flask app, rather than just the single page apps contained in the examples? I've searched Google, but haven't come up with anything...

Any thoughts would be helpful.

[1]: https://sentry.io/share/issue/69f5d9a7285c4d43bd55d61a4d799bee/

**Comment by viniciuschiele** [comment]
Looking at the logs you provided, the error seems to be coming from this line

```python
current_app.sentry.captureException()
```
I think you should replace by this:
```python
scheduler.app.sentry.captureException()
```
Let me know if that works.
