### ISSUE TITLE
Multiple Processes Flask UWSGI

### ISSUE THREAD

**Issue by ufo911** [viniciuschiele/flask-apscheduler#79]
Hello,
I am running web app with Flask with 4 processes and scheduler is running also 4 times, how to attach scheduler for only on a 1 process ?

**Comment by viniciuschiele** [comment]
Hi,

You need to implement it by yourself, you could use some sort of lock mechanism to control that.
For example, each instance could try to create a file (same path, same filename), the first one that manages to create will be the active scheduler, you can also do that with socket, database, redis, ...

I hope this helps you.

**Comment by viniciuschiele** [comment]
Hi,
The concept is the same, you open a port in the server, only one process can open the same port at a time, so the first process that opens the port is the scheduler.

You can find an example here

**Comment by ufo911** [comment]
@viniciuschiele 
It worked for me with socket

**Comment by ufo911** [comment]
But if there is other possible solution to add with the apischeduler would be great (to specify to run multiple or single)

**Comment by viniciuschiele** [comment]
Agreed, I will think about it.

Thanks!

**Comment by ufo911** [comment]
https://stackoverflow.com/questions/24352634/would-starting-apscheduler-in-a-uwsgi-app-end-up-with-one-scheduler-for-each-wor?noredirect=1&lq=1 

Here is mules mentioned too

**Comment by viniciuschiele** [comment]
Thanks for sharing that.

**Comment by albinmedoc** [comment]
> @viniciuschiele
> It worked for me with socket

Can you show a code snippet how you managed to make it work?

**Comment by ufo911** [comment]
@albinmedoc 


```
from flask import Flask, Blueprint, g, redirect, request, \
    session, abort, render_template, url_for, Response, make_response, send_from_directory

import urllib.request
import ssl
import time
import atexit
import os
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger

app = Flask(__name__, template_folder='../templates')

def print_date_time():
    context = ssl._create_unverified_context()
    with urllib.request.urlopen('https://someurl.com',context=context) as a:
        co = a.getcode()
    with open("static/bmidata.txt", "a+") as f:
        f.write(str(co) + "  " + str(time.strftime("%A, %d. %B %Y %I:%M:%S %p")) + "\n")

    print(str(co) + "  " + str(time.strftime("%A, %d. %B %Y %I:%M:%S %p")))

@app.before_first_request
def run_scheduler():
    scheduler = BackgroundScheduler()
    scheduler.start()
    scheduler.add_job(
    func=print_date_time,
    trigger=IntervalTrigger(seconds=60),
    id='printing_job',
    name='Print date and time every five seconds',
    replace_existing=True)
#   Shut down the scheduler when exiting the app
    atexit.register(lambda: scheduler.shutdown())

@app.route('/<path:filename>')
def send_file(filename):
    return send_from_directory(app.static_folder, filename)

if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by Pysion-lin** [comment]
> @albinmedoc
> 
> @ albinmedoc
> 
> ```
> from flask import Flask, Blueprint, g, redirect, request, \
>     session, abort, render_template, url_for, Response, make_response, send_from_directory
> 
> import urllib.request
> import ssl
> import time
> import atexit
> import os
> from apscheduler.schedulers.background import BackgroundScheduler
> from apscheduler.triggers.interval import IntervalTrigger
> 
> app = Flask(__name__, template_folder='../templates')
> 
> def print_date_time():
>     context = ssl._create_unverified_context()
>     with urllib.request.urlopen('https://someurl.com',context=context) as a:
>         co = a.getcode()
>     with open("static/bmidata.txt", "a+") as f:
>         f.write(str(co) + "  " + str(time.strftime("%A, %d. %B %Y %I:%M:%S %p")) + "\n")
> 
>     print(str(co) + "  " + str(time.strftime("%A, %d. %B %Y %I:%M:%S %p")))
> 
> @app.before_first_request
> def run_scheduler():
>     scheduler = BackgroundScheduler()
>     scheduler.start()
>     scheduler.add_job(
>     func=print_date_time,
>     trigger=IntervalTrigger(seconds=60),
>     id='printing_job',
>     name='Print date and time every five seconds',
>     replace_existing=True)
> #   Shut down the scheduler when exiting the app
>     atexit.register(lambda: scheduler.shutdown())
> 
> @app.route('/<path:filename>')
> def send_file(filename):
>     return send_from_directory(app.static_folder, filename)
> 
> if __name__ == '__main__':
>     app.run(debug=True)
> ```

this code can not solve the problem
