### ISSUE TITLE
Please update PYPI archive with the latest GIT files 

### ISSUE THREAD

**Issue by andreicalistru** [viniciuschiele/flask-apscheduler#80]
It seems that the archive from https://pypi.org/project/Flask-APScheduler doesn't contain the latest changes merged into master, e.g. the API_PREFIX config option.
Could you please update it?

Thank you!

**Comment by viniciuschiele** [comment]
Sorry for the delay.

It is done, version 1.9.0

**Comment by andreicalistru** [comment]
Thanks a lot!
Works like a charm.
Would be nice if the endpoints could have some prefixes as well, like a default 'scheduler.x' and make it editable too.
If you list all your flask routes, they look disorderly, because are listed in alphabetic order and they get mixed with the other existing routes.
I might do a PR if anyone is interested.

**Comment by viniciuschiele** [comment]
Not sure If I've followed you.

Why would you like to add a prefix to the endpoints? Can you give an example of an URL?

**Comment by andreicalistru** [comment]
Consider running the "**flask routes**" cli command, you will see a table with 3 columns: **Endpoint**, **Methods**, **Rule**.
With the prefix for rules, the URL's look fine. Only the **Endpoints** look messy now.
If you are using a  flask blueprint for your routes, you would have the blueprint name as a prefix in all of your Endpoints. Since the scheduler is not using a blueprint, all scheduler Endpoints are displayed alphabetically, not grouped after it's functionality (scheduler, blueprint name, etc).
Here is an example to make an idea of what I'm speaking about (See the endpoints starting with **api.** which are the ones that are generated with blueprint, while the ones generated from flask-scheduler appear above and below the **api.** prefixed endpoints. It's more about the visibility/readability or grouping endpoints together):

```
Endpoint                        Methods                 Rule
------------------------------  ----------------------  --------------------------------------------
add_job                         POST                    /api_prefix/scheduler/jobs
api.aboutcontroller             GET                     /api_prefix/status/about
api.consulcontroller            DELETE, GET, POST, PUT  /api_prefix/consul/<string:key>
api.dashboardcontroller         GET, POST               /api_prefix/dashboards/<string:dashboard_id>
api.dashboardlistcontroller     GET                     /api_prefix/dashboards
api.healthcontroller            GET                     /api_prefix/status/health
api.ping                        GET                     /api_prefix/status/ping
delete_job                      DELETE                  /api_prefix/scheduler/jobs/<job_id>
get_job                         GET                     /api_prefix/scheduler/jobs/<job_id>
get_jobs                        GET                     /api_prefix/scheduler/jobs
get_scheduler_info              GET                     /api_prefix/scheduler
pause_job                       POST                    /api_prefix/scheduler/jobs/<job_id>/pause
resume_job                      POST                    /api_prefix/scheduler/jobs/<job_id>/resume
run_job                         POST                    /api_prefix/scheduler/jobs/<job_id>/run
update_job                      PATCH                   /api_prefix/scheduler/jobs/<job_id>
```

**Comment by viniciuschiele** [comment]
Now I see what you mean, that makes sense.

I'm wondering now if **SCHEDULER_API_PREFIX** should be by default '**scheduler**' too so we could have two variables **SCHEDULER_API_PREFIX** and **SCHEDULER_ENDPOINT_PREFIX** both defaulted to **'scheduler'**

**Comment by andreicalistru** [comment]
I think that a default (editable) value for routes would be a good addition too.
MAYBE someone is already using **scheduler** as a route and it would end up in conflict with the hard coded routes from this package.
For **SCHEDULER_ENDPOINT_PREFIX**, I would add a default value for sure, e.g. **scheduler**, while for the **SCHEDULER_API_PREFIX**, probably an extra variable  **SCHEDULER_RULE_PREFIX** might be a better fit with default value to **scheduler**.
The rule would be a combination of SCHEDULER_API_PREFIX + SCHEDULER_RULE_PREFIX.

**Comment by viniciuschiele** [comment]
#81 #82
