### ISSUE TITLE
How to add job using the date trigger

### ISSUE THREAD

**Issue by guyturner797** [viniciuschiele/flask-apscheduler#83]
Trying to add a job like this:
`scheduler.add_job(id='jobx', func=show_users, trigger='date')`

How can I pass a datetime object to call the job? Currently if I run it as above it executes immediately.

APScheduler documentation for it here:
http://apscheduler.readthedocs.io/en/latest/modules/triggers/date.html

**Comment by viniciuschiele** [comment]
Hi,

Try this:
```python
sched.add_job(id='jobx', func=show_users, trigger='date', run_date=date(2018, 7, 31))
```

**Comment by guyturner797** [comment]
Great thank!

**Comment by hari17691a0447** [comment]
in my project i want to schedule many tasks to run on particular date and time .
i want create a jobs pool and append all created jobs into the pool, and i want automate them on particular date and time.
how could i do above job.
please help me.
