### ISSUE TITLE
work failed in Flask UWSGI 

### ISSUE THREAD

**Issue by GuiBin2013** [viniciuschiele/flask-apscheduler#84]
hi 
I use flask-apscheduler in my project. When I use it in development mode , it can work well. But when i run the flask by uwsgi , it can't work. It can add and del , but never run the cron orinteral task at the appointed time and never raise exception.

this is my uwsgi.ini file and flask-apscheduler init flie.
`
from flask import Flask, jsonify
from flask_apscheduler import APScheduler

scheduler = APScheduler()
app = Flask(__name__)
app.config.from_object("config.Config")
scheduler.init_app(app)
scheduler.start()
`

`[uwsgi]
socket=127.0.0.1:9088
processes=2
master=true
chdir=/data/project/
module=manage
callable=app
enable-threads=true
uid=1000
gid=1000
buffer-size=65536
daemonize=/data/log/uwsgi/center.log`

I have read others' issue , and try to add **enable-threads=true** . but it also can't work. 
It has borded me for 2days. Is there any solutions?  Or is there some successful examples in 'uwsgi + flask-apscheduler' .

Thank you very much!!

**Comment by viniciuschiele** [comment]
Hi,

Sorry for the delay.

I've just tested it with the example **jobs.py** and it works great.

That's the command line I used for uwsgi.

```
 uwsgi --socket=127.0.0.1:9088 --module=jobs --callable=app --enable-threads --master
```

I also tested it with a *cron* job and it works fine for me:

```python
    JOBS = [
        {
            'id': 'job1',
            'func': 'jobs:job1',
            'args': (1, 2),
            'trigger': 'cron',
            'second': '*',
        }
    ]
```

**Comment by compressionist** [comment]
Hi, 
what version of uwsgi are you using? 
I tried to run jobs.py with uwsgi 2.0.17.1 on centos7 and Mac, and unfortunately job1 is not running, I also have the same issue with my code (so, without uwsgi 2.0.17.1  everything works fine).

Thank you in advance!

**Comment by viniciuschiele** [comment]
Same version here.

If you are trying to run the **jobs.py** with uwsgi, you need to remove this line **if __name__ == '__main__':**

**Comment by compressionist** [comment]
Thanks, now it works, but it's very difficult to get out of the application (ie, Ctrl+C does not work): Stopped it with Ctrl+Z, and then "kill -9 ...". So, it might be better to use "mule" in the uwsgi command line, am I right?

uwsgi --socket = 127.0.0.1: 9088 --mule=jobs.py --callable=app --enable-threads --master

**Comment by viniciuschiele** [comment]
That doesn't happen for me, the process gets kill straight away

**Comment by compressionist** [comment]
Finally, I figured out how to solve the problem with uwsgi shutdown, the line “app.run ()” should also be removed from the flask application (e.g., jobs.py). This also resolved the other two deployment issues: “OSError: [Errno 48] Address is already in use” and “WARNING: do not use the development server in a production environment (i.e, when we need to switch to production mode using "--http = localhost:8080").    For more information, see here:

http://flask.pocoo.org/docs/1.0/quickstart/#a-minimal-application
