### ISSUE TITLE
MySQL server has gone away 

### ISSUE THREAD

**Issue by zc442200** [viniciuschiele/flask-apscheduler#86]
I think this question should be MySQL 8 hour problem.
How should I configure.

**Comment by dyzne** [comment]
This my <my.cnf> file  configure:
 [mysqld]
wait_timeout = 31536000
interactive_timeout = 31536000

Then restart mysql server.

**Comment by zc442200** [comment]
This is my solution:
`    app.config['SCHEDULER_JOBSTORES'] = {
        'default': SQLAlchemyJobStore(url=app.config.get('SQLALCHEMY_DATABASE_URI'),
                                      tablename='aps_job', engine_options=dict(pool_pre_ping=True))
    }
`
http://docs.sqlalchemy.org/en/latest/core/engines.html
