### ISSUE TITLE
gunicorn --preload  task don't work

### ISSUE THREAD

**Issue by dyzne** [viniciuschiele/flask-apscheduler#87]
In multiple process, to avoid generate multiple scheduler instance and avoid execute task multiple times, i try to execute gunicorn like this:
   gunicorn -b 127.0.0.1:5000 manage:app -k gevent -w 8 --preload
Although only one scheduler was generated,but  task don't work.
Then i try use lock to avoid generate mutiple shceduler instance , result is same, task don't work.
How should me to resolve this problem?

**Comment by dyzne** [comment]
This is my configure:
    SCHEDULER_JOBSTORES = {
        'default': SQLAlchemyJobStore(url='mysql+pymysql://xxx/xx')
    }
    SCHEDULER_EXECUTORS = {
        'default': {'type': 'threadpool', 'max_workers': 20}
    }
    SCHEDULER_JOB_DEFAULTS = {
        'coalesce': False,
        'max_instances': 3,
    }

**Comment by zhaoyaqiong** [comment]
I have the same problem.
In Python 3.5.2; APScheduler 3.5.3;  Flask  1.0.2; Flask-APScheduler 1.10.1
But I'm not using '--preload'.
This is my command for run flask:
```shell
gunicorn -w 8 -b 127.0.0.1:5000 -k gevent run:app
```
This is my configure:
```python
SCHEDULER_JOBSTORES = {
        'default': SQLAlchemyJobStore(url='postgresql://xxx:xxx@xxx/xxx')
    }

SCHEDULER_EXECUTORS = {
        'default': {'type': 'threadpool', 'max_workers': 20}
    }

SCHEDULER_JOB_DEFAULTS = {
        'coalesce': False,
        'max_instances': 3
    }
```

**Comment by comtihon** [comment]
`when_ready` gunicorn callback may help you.
I am using raw scheduler (without this flask wrapper)

**Comment by albinmedoc** [comment]
@comtihon
Can you show how you made it work?

**Comment by comtihon** [comment]
@albinmedoc
Here is gunicorn's [when_ready](http://docs.gunicorn.org/en/stable/settings.html#when-ready), where I start the job.
```
def when_ready(server):
    app.injector.get(Beat).schedule_scraping()
```
And here is my job. It is configured at the start time and starts when application is ready.
```
@singleton
class BackgroundBeat(Beat):
    @inject
    def __init__(self, image_scraper: ImageScraper) -> None:
        super().__init__()
        self.scheduler = GeventScheduler(timezone=utc)
        self.scheduler.add_job(image_scraper.queue, 'interval', kwargs={'app': datapi.app}, seconds=1)

    def schedule_scraping(self):
        self.scheduler.start()
```
