### ISSUE TITLE
How to remove a endless-loop job when trigger='date'？

### ISSUE THREAD

**Issue by githubcyc** [viniciuschiele/flask-apscheduler#90]
my  endless-loop job like this:
```
def job1(a, b):
    while True:
        print(str(a) + ' ' + str(b))
```

schedule:
```
 scheduler.add_job(id='1', func=job1, args=(1, 2), trigger='date', next_run_time=datetime.datetime.now())
```

but `remove_job` doesn't work and raise `JobLookupError: 'No job by the id of 1 was found'`
```
 scheduler.remove_job(id='1')
```
What can i do to stop this endless-loop `job1`?
❤️ Thanks for everyone!

**Comment by viniciuschiele** [comment]
Hi @githubcyc 

APScheduler won't kill the job that is currently running, when you remove a job it will only prevent it gets triggered the next time.

A workaround would be to check if *job1* is still in the scheduler.

```python
def job1(a, b):
    while scheduler.get('job1'):
        print(str(a) + ' ' + str(b))
```
