### ISSUE TITLE
Make Flask context available in nested methods

### ISSUE THREAD

**Issue by KietnaQuTak** [viniciuschiele/flask-apscheduler#91]
Hello. I have found similar topics which helped me to figure out how to access Flask context in APS scheduled jobs. Right now I'm able to schedule a job which for example access any Flask configuration variable like in example bellow:

```
def scheduler_simple_test():
    from app import scheduler
    from flask import current_app
    from config import ConfigKeys
    with scheduler.app.app_context():
        print('test', str(current_app.config[ConfigKeys.BABEL_DEFAULT_LOCALE]))
```

Unfortunately this approach does not work when APS job is trying to trigger any function that requires Flask context. In some cases there are several nested methods which depends on each other (one is executing another), for example: APS job => Subscription.actions_renew() => Button.create_on_static() => Button.get_code_script_file() => Button.get_settings(). So APS job is executing one method which is executing other methods which also requires Flask context and so on.

**My question is:** Do I need to implement app_context() in every single method that is executed after APS job executes another method which requires Flask context for nested methods (like bellow)?

```
def scheduler_nested_test():
    from app import scheduler
    with scheduler.app.app_context():
        Subscription.actions_renew()
```

**Comment by KietnaQuTak** [comment]
Thank You for answer. In provided example I need only access to configuration variables. Database access somehow is working by it's own after providing ```db.app = app``` before executing ```db.init_app(app)``` in ```create_app()``` method.

My APS job **(A)** is executing ```Subscription.actions_renew()``` **(B)** with app_context(). This method is executing ```Button.create_on_static()``` **(C)** which executes ```Button.get_code_script_file()``` **(D)** which finally executes ```Button.get_settings()``` **(E)**. Settings are required only in ```Button.get_settings()``` so do I need to implement app_context() only in ```get_settings()``` or in all methods executed along the way like in simplified example bellow:

**(A)**
```
def aps_job():
	with scheduler.app.app_context():
		Subscription.actions_renew()
```

**(B)**
```
def actions_renew(cls):
	with scheduler.app.app_context():
		Button.create_on_static()
```

**(C)**
```
def create_on_static(cls):
	with scheduler.app.app_context():
		Button.get_code_script_file()
```

**(D)**
```
def get_code_script_file(cls):
	with scheduler.app.app_context():
		Button.get_settings()
```

**(E)**
```
def get_settings(cls):
	with scheduler.app.app_context():
		print('test', str(current_app.config[ConfigKeys.BUTTON_SETTINGS]))
```

**Comment by viniciuschiele** [comment]
if I understood correctly, you just need to create a context in your job method which in this case is **aps_job**, **get_settings** will be able to get a Flask app from **current_app**.

If you are getting an error in **get_settings***, can you provide the exception?

**Comment by KietnaQuTak** [comment]
It happens that it was my oversight so cased closed. :-) I really appreciate Your help :+1:  After debugging code more carefully I have figure out that **Button.get_settings()** method is also checking value of **request.url** which is obviously not available when triggered from background task even with provided app_context.

Right now I can confirm that using **with scheduler.app.app_context()** only in APS job is enough (like in code bellow). One just need to remember not to use any Flask variables that are not available without request. ;-)
```
def aps_job():
	with scheduler.app.app_context():
		Subscription.actions_renew()
```
