### ISSUE TITLE
How to add/remove SQLAlchemyJobStore on the fly?

### ISSUE THREAD

**Issue by compressionist** [viniciuschiele/flask-apscheduler#92]
Hi, 

I need to create a separate “jobstore” database for each user. 
The problem is that I only get users while my API is running. 
That is, I need to add a “jobstore” for each new user, and then add / update / delete jobs, and also remove the user's “jobstore” if the user is not active for a long time. 
So, how can I implement the above using flask-apscheduler?
Can you provide an example of how to add a “jobstore” or remove a “jobstore” on the fly?

Thank you in advance!
Eugene

**Comment by viniciuschiele** [comment]
Hi,

There are two methods in APScheduler to add and remove job stores.

**add_jobstore**, **remove_jobstore**

Using Flask-APScheduler you can access those methods like that:

```python
scheduler = APScheduler()
scheduler.scheduler.add_jobstore()
```

For further info check this link out: https://apscheduler.readthedocs.io/en/latest/extending.html
