### ISSUE TITLE
Got 'Warning: (1300, "Invalid utf8mb4 character string: '800495'")

### ISSUE THREAD

**Issue by SSCedric** [viniciuschiele/flask-apscheduler#95]
environment:
centos 7
python3.6
flask1.0.2
flask_sqlalchemy2.3.2
flask_scheduler1.10.1
uWSGI 2.0.17.1

When I add an 'data' job, then I got warning:
Got 'Warning: (1300, "Invalid utf8mb4 character string: '800495'")

Then I checked out mysql, the job has stored in it, but didn't run the task on time.

It worked on development environment, but didn't with uWsgi.

**Comment by viniciuschiele** [comment]
Hi,

The warning and the fact that it doesn't work with uwsgi seems to be different things.

There are some issues here related to uwsgi, have you already had a look at them?

https://github.com/viniciuschiele/flask-apscheduler/issues/37
https://github.com/viniciuschiele/flask-apscheduler/issues/52
https://github.com/viniciuschiele/flask-apscheduler/issues/84

Let me know how that goes.
