### ISSUE TITLE
Dynamic loading parameters

### ISSUE THREAD

**Issue by qxyuan** [viniciuschiele/flask-apscheduler#97]
Hi

Can the parameter id/func/args/trigger/seconds of apscheduler in flask be changed into dynamic? If so, what should we do?

Thank you in advance!

**Comment by viniciuschiele** [comment]
Hi,

Yes, they can be changed on the fly, you can use REST API for it.

Example using curl

```
curl -X PATCH http://localhost:8080/scheduler/jobs/<job_id>
{
    "trigger": "seconds",
    "args": [1, 2]
}
```

Have a look at the unit tests, there are some testing the API

https://github.com/viniciuschiele/flask-apscheduler/blob/master/tests/test_api.py#L115

**Comment by qxyuan** [comment]
Hi

My parameters are dynamically received through routing, and every time I receive them, I add a timer. I do this，Is it appropriate to do this?

`def job1(args):
    print(args)
    print("I am working:%s" % (datetime.datetime.now()))

def jobfromparm(**jobargs):
    id = jobargs['id']
    args = jobargs['args']
    seconds = jobargs['seconds']
    trigger = jobargs['trigger']
    print('add job:', id)
    job = scheduler.add_job(func=job1, trigger=trigger, seconds=seconds, args=args, id=id)
    return "success"

@app.route("/add", methods= ['POST'])
def add_job():
    data = request.get_json(force=True)
    job = jobfromparm(**data)
    return jsonify({"ok": "success"})`

**Comment by viniciuschiele** [comment]
Yes, that's fine, you can also update an existing job.

Worth mention that Flask-APScheduler already exposes endpoints to add/delete/update jobs, you just need to enable it
```
SCHEDULER_API_ENABLED = True 
```

**Comment by qxyuan** [comment]
modify_job(job_id, **data)
What parameters does data contain?Can you give an example?

**Comment by MaazMS** [comment]
```
from flask import Flask
from flask_apscheduler import APScheduler, api


class Config(object):
    JOBS = [
        {
            'id': 'job5',
            'func': 'f_s_api.view:job1',
            'trigger': 'interval',
            'seconds': 10
        }
    ]
   
    SCHEDULER_API_ENABLED = True

def job1():
    print('job add') 
    
if __name__ == '__main__':
    app = Flask(__name__)
    app.config.from_object(Config())
    scheduler = APScheduler()
    # it is also possible to enable the API directly
    # scheduler.api_enabled = True
    scheduler.init_app(app)
    scheduler.start()
    app.run(debug= True , port= 8080)
``` 

how to add job using flask apscheduler by  using api
